#!/usr/bin/env bash
#
# Build the FlowGate client into client/dist (multi-page: index/main/settings).
# The staging server serves the resulting dist/ as static files on the same
# origin, so the client talks to the API via a relative base URL.
#
# IMPORTANT: client/.env holds a dev machine's API URL. This script writes
# .env.production.local (Vite's highest-precedence env file) so the build does
# NOT inherit that dev URL.
#
# Usage:
#   ./build.sh                                  # API base = /flowgate (same-origin)
#   ./build.sh https://stg.example.com/flowgate # absolute base (e.g. outbound links)
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# systemd runs this from a non-interactive login shell (ExecStartPre `bash -lc`)
# which does NOT source ~/.bashrc, so nvm's node/npm are off PATH there ("npm:
# command not found"). Load nvm explicitly when npm is missing. Interactive
# manual runs already have npm, so this is a no-op for them.
if ! command -v npm >/dev/null 2>&1; then
    export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
    # shellcheck source=/dev/null
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
fi

API_BASE="${1:-/flowgate}"

# Highest-precedence Vite env file — overrides the dev client/.env at build time.
cat > .env.production.local <<EOF
# Generated by build.sh — do not edit. Sets the API base for the built client.
VITE_API_BASE_URL=$API_BASE
EOF

npm install
npm run build   # vue-tsc type-check + vite build → dist/

echo "Build complete → client/dist  (API base: $API_BASE)"
