-- T2/TR2 global document types (flowgate.default.0565 T0016).
INSERT INTO document_types (project_id,type_code,type_name,series,is_system,is_active,sort_order,color,created_at,updated_at) SELECT NULL,'T2','변경제안 지시','instruction',1,1,35,'#0891b2',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM document_types WHERE project_id IS NULL AND type_code='T2');
INSERT INTO document_type_names (document_type_id,locale,type_name) SELECT id,'ko','변경제안 지시' FROM document_types WHERE project_id IS NULL AND series='instruction' AND type_code='T2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_descriptions (document_type_id,locale,description) SELECT id,'ko','TR2 변경제안을 작성하고 승인 후 적용할 변경을 지시한다.' FROM document_types WHERE project_id IS NULL AND series='instruction' AND type_code='T2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_names (document_type_id,locale,type_name) SELECT id,'en','Change Proposal Instruction' FROM document_types WHERE project_id IS NULL AND series='instruction' AND type_code='T2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_descriptions (document_type_id,locale,description) SELECT id,'en','Direct a TR2 proposal; changes apply after approval.' FROM document_types WHERE project_id IS NULL AND series='instruction' AND type_code='T2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_names (document_type_id,locale,type_name) SELECT id,'ja','変更提案指示' FROM document_types WHERE project_id IS NULL AND series='instruction' AND type_code='T2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_descriptions (document_type_id,locale,description) SELECT id,'ja','TR2 の変更提案を指示し、承認後に変更を適用する。' FROM document_types WHERE project_id IS NULL AND series='instruction' AND type_code='T2' ON CONFLICT DO NOTHING;
INSERT INTO document_types (project_id,type_code,type_name,series,is_system,is_active,sort_order,color,created_at,updated_at) SELECT NULL,'TR2','변경제안','work',1,1,25,'#0284c7',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM document_types WHERE project_id IS NULL AND type_code='TR2');
INSERT INTO document_type_names (document_type_id,locale,type_name) SELECT id,'ko','변경제안' FROM document_types WHERE project_id IS NULL AND series='work' AND type_code='TR2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_descriptions (document_type_id,locale,description) SELECT id,'ko','소스 변경을 제안하고 사람 승인 후 적용하는 문서.' FROM document_types WHERE project_id IS NULL AND series='work' AND type_code='TR2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_names (document_type_id,locale,type_name) SELECT id,'en','Change Proposal' FROM document_types WHERE project_id IS NULL AND series='work' AND type_code='TR2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_descriptions (document_type_id,locale,description) SELECT id,'en','Propose source changes for application after human approval.' FROM document_types WHERE project_id IS NULL AND series='work' AND type_code='TR2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_names (document_type_id,locale,type_name) SELECT id,'ja','変更提案' FROM document_types WHERE project_id IS NULL AND series='work' AND type_code='TR2' ON CONFLICT DO NOTHING;
INSERT INTO document_type_descriptions (document_type_id,locale,description) SELECT id,'ja','ソース変更を提案し、人の承認後に適用する文書。' FROM document_types WHERE project_id IS NULL AND series='work' AND type_code='TR2' ON CONFLICT DO NOTHING;
