# -*- coding: utf-8 -*-
"""Regenerate the MySQL/MariaDB and PostgreSQL migration sets from the SQLite source.

Group 0088 (TR0007). This is the single, reproducible source of truth for
``server/sql/migrations/{mysql,postgres}``. Re-run it whenever a new SQLite
migration is added so the dialect sets stay in sync.

Two deterministic steps:

  1. ``sqloader convert`` (sqloader==0.2.15) translates each SQLite migration to
     the target dialect (AUTOINCREMENT->AUTO_INCREMENT/SERIAL, INSERT OR IGNORE->
     INSERT IGNORE / ON CONFLICT DO NOTHING, datetime('now')->CURRENT_TIMESTAMP,
     identifier quoting, ...).

  2. Post-process: drop every non-comment ``PRAGMA ...`` statement line.

Why step 2 exists (sqloader 0.2.15 convert defect, see TR0007 §2-2): the converter
does NOT reliably remove ``PRAGMA foreign_keys`` on non-SQLite targets. ``= OFF``
variants are left verbatim, and a following INSERT's idempotency clause can be
mis-attached to the PRAGMA, producing broken statements such as
``PRAGMA foreign_keys = OFF ON CONFLICT DO NOTHING;``. PRAGMA is SQLite-only, so
removing these whole lines is the correct fix.

Lossless proof (TR0007 §2-2, finding #4): dropping the PRAGMA *line* never strips a
real INSERT's conflict handling, because each seed INSERT carries its own
IGNORE / ON CONFLICT clause on its own statement. ``--verify`` re-checks this
statement-by-statement across all files before writing. The mis-attached clause on
a PRAGMA line is a *duplicate* of the converter's already-correct clause on the
real INSERT, so deleting the PRAGMA line removes only the duplicate.

Usage (run from server/):
    python tools/regen_dialect_migrations.py            # regenerate in place
    python tools/regen_dialect_migrations.py --verify   # regenerate to temp + diff, no write
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SERVER = os.path.dirname(HERE)
MIG = os.path.join(SERVER, "sql", "migrations")
SRC = os.path.join(MIG, "sqlite")

# (target dir name, sqloader --to value)
TARGETS = [("mysql", "mysql"), ("postgres", "postgresql")]

# Migrations whose data transform is handled by portable Python at startup
# (server/modules/flow_gate/db/backfills/) instead of SQL, because the SQLite
# source uses JSON DML that does not translate (B0091, migration 037). For every
# non-SQLite target we emit a documented no-op stub in place of the converter's
# (broken) output. The sqlite source is left untouched.
_CODE_HANDLED_IDS = {"037"}

# SQLite-only JSON DML the converter cannot translate (table-valued json_each and
# the aggregate json_group_array / json_array_length). If any file NOT in
# _CODE_HANDLED_IDS reaches a non-SQLite target still carrying these, fail loudly
# at regen time instead of silently emitting broken SQL that aborts startup —
# this is exactly the B0091 root cause (037 slipped through verbatim).
_UNSUPPORTED_DML = re.compile(r"(?i)\b(json_each|json_group_array|json_array_length)\s*\(")

# SQLite-only procedural SQL the converter passes through verbatim: a CREATE
# TRIGGER (SQLite's trigger grammar — the WHEN guard clause and the RAISE()
# function — is not valid MariaDB/PostgreSQL syntax and aborts startup with a
# 1064 parse error). This is the *same class* of defect as _UNSUPPORTED_DML but
# for schema rather than data (B0091, group 0091, migration 041). If any file
# reaches a non-SQLite target still carrying one, fail loudly at regen time:
# either re-express the invariant as a portable CHECK (preferred, as 041 does),
# or author the dialect-specific trigger by hand. Never ship the verbatim SQLite
# trigger — that just moves the boot failure to the next migration.
_UNSUPPORTED_TRIGGER = re.compile(r"(?im)^\s*CREATE\s+TRIGGER\b|\bRAISE\s*\(")

# PostgreSQL-only regression guards (B0095, group 0095). After the postgres fix-up steps run,
# none of these should remain; if one does it means a new migration introduced a JSON construct
# the post-processor does not yet handle, and shipping it would abort the boot migration.
#   * an uncast ->/->> JSON access (left operand not produced by a ::jsonb/::json cast)
#   * a verbatim SQLite/MySQL json_array(/json_object( constructor
_PG_UNCAST_ARROW = re.compile(r"(?i)(?<!:)\b\w+(?:\.\w+)?\s*->>?\s*'")
_PG_SQLITE_JSON_CTOR = re.compile(r"(?i)\bjson_(?:array|object)\s*\(")
#   * a GROUP BY on a non-PK column (a bare `<alias>.doc_id`) that PostgreSQL rejects unless the
#     grouping key is the table's PRIMARY KEY (fix_pg_groupby_pk rewrites doc_id -> id)
_PG_GROUPBY_NONPK = re.compile(r"(?i)\bGROUP\s+BY\s+\w+\.doc_id\b")

# Cross-dialect no-op: a comment-only file can trip "can't execute an empty query".
_NOOP_STUB = (
    "-- {fname}  ({target} — intentional no-op, generated by regen_dialect_migrations.py)\n"
    "--\n"
    "-- The data transform for this migration is handled by portable Python at\n"
    "-- startup (server/modules/flow_gate/db/backfills/) because the SQLite source\n"
    "-- uses JSON DML that does not translate to this backend (B0091). Kept as a\n"
    "-- documented no-op so the migration ledger stays unbroken.\n"
    "SELECT 1;\n"
)


def _migration_id(fname: str) -> str:
    """Numeric id prefix of a migration filename (e.g. '037' from '037_foo.sql')."""
    return fname.split("_", 1)[0]

_PRAGMA_LINE = re.compile(r"\s*PRAGMA\b")
_INSERT_HEAD = re.compile(r"(?im)^\s*INSERT\b")

# MySQL/MariaDB cannot index a TEXT/BLOB column without a prefix length, so a TEXT
# column used as PRIMARY KEY / UNIQUE / FOREIGN KEY makes the migration fail outright
# (group 0088: "MySQL TEXT-PK"). sqloader 0.2.15 convert leaves these as TEXT. Step 3
# below promotes every *keyed* TEXT column to VARCHAR so the schema applies. 191 is the
# classic utf8mb4-safe single-column index length (191*4 = 764 B) and keeps the one wide
# composite key (4 text cols) under MariaDB's 3072-byte InnoDB limit. PostgreSQL indexes
# TEXT natively, so this step is MySQL-only.
_VARCHAR_LEN = 191
# A wide composite key (≥4 text members) of VARCHAR(191) utf8mb4 would exceed MariaDB's
# 3072-byte InnoDB key limit (e.g. the 6-column numbering counters PK). Such members get a
# shorter length; they are short identifiers/codes and carry no FK (so no type-match concern).
_WIDE_KEY_THRESHOLD = 4
_WIDE_VARCHAR_LEN = 64
_KEY_KEYWORDS = re.compile(r"(?i)\b(PRIMARY\s+KEY|UNIQUE|REFERENCES)\b")
_COMPOSITE_KEY = re.compile(
    r"(?i)\b(?:PRIMARY\s+KEY|FOREIGN\s+KEY|UNIQUE(?:\s+KEY\s+\w+)?)\s*\(([^)]*)\)"
)
_COL_DEF = re.compile(r"(?i)^\s*[`\"]?(\w+)[`\"]?\s+TEXT\b")
_CREATE_TABLE = re.compile(r"(?i)^\s*CREATE\s+TABLE\b")
_ALTER_ADD_COL = re.compile(
    r"(?is)(ALTER\s+TABLE\s+[`\"]?(\w+)[`\"]?\s+ADD\s+COLUMN\s+"
    r"(?:IF\s+NOT\s+EXISTS\s+)?[`\"]?(\w+)[`\"]?\s+)TEXT\b"
)
# ADD COLUMN <col> TEXT ... REFERENCES ... (inline FK, possibly spanning lines).
_ALTER_ADD_FK = re.compile(
    r"(?is)ALTER\s+TABLE\s+[`\"]?(\w+)[`\"]?\s+ADD\s+COLUMN\s+"
    r"(?:IF\s+NOT\s+EXISTS\s+)?[`\"]?(\w+)[`\"]?\s+TEXT\b[^;]*?\bREFERENCES\b"
)


def strip_pragma(text: str) -> str:
    """Drop every line whose first non-space token is PRAGMA (the step-2 fix)."""
    return "".join(
        line for line in text.splitlines(keepends=True) if not _PRAGMA_LINE.match(line)
    )


# Partial (filtered) UNIQUE indexes — CREATE UNIQUE INDEX ... ON t(cols) WHERE pcol IS NULL —
# enforce a "≤1 row where pcol IS NULL" invariant. SQLite and PostgreSQL support them; MySQL
# does NOT. sqloader 0.2.15 convert leaves the WHERE verbatim, so the migration aborts on
# MariaDB. Emulate the exact semantics with a STORED generated column that holds the key only
# when pcol IS NULL (NULL otherwise) plus a plain UNIQUE index on it: MySQL allows many NULLs
# in a UNIQUE index, so per-pcol rows stay unconstrained while the global rows are unique.
_PARTIAL_UNIQUE_INDEX = re.compile(
    r"(?is)\bCREATE\s+UNIQUE\s+INDEX\s+(?P<ine>IF\s+NOT\s+EXISTS\s+)?(?P<name>\w+)\s+"
    r"ON\s+(?P<table>\w+)\s*\((?P<cols>[^)]*)\)\s*"
    r"WHERE\s+(?P<pcol>\w+)\s+IS\s+(?P<notnull>NOT\s+)?NULL\s*;"
)


def fix_mysql_partial_indexes(text: str) -> str:
    """Rewrite partial UNIQUE indexes for MySQL/MariaDB.

    * ``WHERE pcol IS NOT NULL`` is equivalent to a plain UNIQUE index: MySQL/MariaDB
      already treat NULLs as distinct, so rows with NULL pcol are unconstrained either
      way. Drop the WHERE.
    * ``WHERE pcol IS NULL`` needs the generated-column emulation: the key is materialised
      only for the NULL-pcol rows (NULL otherwise), so the global rows stay unique while
      per-pcol rows are unconstrained.
    """
    def repl(m: "re.Match") -> str:
        ine = m.group("ine") or ""
        name = m.group("name")
        table = m.group("table")
        cols = ", ".join(c.strip() for c in m.group("cols").split(","))
        pcol = m.group("pcol")
        if m.group("notnull"):
            return f"CREATE UNIQUE INDEX {ine}{name} ON {table} ({cols});"
        gcol = f"_g_{name}"
        # CONCAT_WS with a control-char separator keeps multi-column keys collision-free.
        return (
            f"ALTER TABLE {table} ADD COLUMN {ine}{gcol} VARCHAR(255) "
            f"GENERATED ALWAYS AS (CASE WHEN {pcol} IS NULL "
            f"THEN CONCAT_WS(CHAR(31), {cols}) ELSE NULL END) STORED;\n"
            f"CREATE UNIQUE INDEX {ine}{name} ON {table} ({gcol});"
        )

    return _PARTIAL_UNIQUE_INDEX.sub(repl, text)


_PARTIAL_NONUNIQUE_INDEX = re.compile(
    r"(?is)(CREATE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?\w+\s+ON\s+[`\"]?\w+[`\"]?\s*\([^)]*\))"
    r"\s*WHERE[^;]*;"
)


def fix_mysql_nonunique_partial_indexes(text: str) -> str:
    """Drop the WHERE filter from non-unique partial indexes for MySQL/MariaDB.

    MySQL has no partial indexes. For a *non-unique* index the filter is only a size/perf
    optimization, never a correctness constraint, so indexing all rows (dropping WHERE) is
    behaviour-equivalent. (UNIQUE partial indexes are handled separately and must NOT be
    stripped — see fix_mysql_partial_indexes.)
    """
    return _PARTIAL_NONUNIQUE_INDEX.sub(r"\1;", text)


_CREATE_TABLE_NAME = re.compile(r"(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`\"]?(\w+)")
_CREATE_INDEX = re.compile(
    r"(?is)CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s+"
    r"ON\s+[`\"]?(\w+)[`\"]?\s*\(([^)]*)\)"
)
_DROP_INDEX = re.compile(
    r"(?i)DROP\s+INDEX\s+(IF\s+EXISTS\s+)?[`\"]?(\w+)[`\"]?\s*(ON\s+[`\"]?\w+[`\"]?)?\s*;"
)
_ALTER_ADD_INDEX = re.compile(
    r"(?is)ALTER\s+TABLE\s+[`\"]?(\w+)[`\"]?\s+ADD\s+(?:CONSTRAINT\s+\w+\s+)?"
    r"(?:UNIQUE|INDEX|KEY|PRIMARY\s+KEY|FOREIGN\s+KEY)\b[^(]*\(([^)]*)\)"
)


class IndexMap:
    """Global record of which (table, column) pairs are indexed, FK-bound, or wide-keyed."""

    def __init__(self):
        self.indexed: dict[str, set[str]] = {}
        self.fk: dict[str, set[str]] = {}
        self.wide: dict[str, set[str]] = {}
        # Maps a transient CREATE-then-RENAME table name to its final name, so a column
        # defined in `X_new` is matched against indexes declared on the renamed-to `X`.
        self.renames: dict[str, str] = {}
        # index name -> table it was created on (for MySQL DROP INDEX ... ON <table>).
        self.index_table: dict[str, str] = {}

    def _add(self, bucket: dict, table: str, cols) -> None:
        bucket.setdefault(table, set()).update(cols)

    def mark(self, table: str, cols: list[str], *, fk: bool = False) -> None:
        cols = [c for c in cols if c]
        self._add(self.indexed, table, cols)
        if fk:
            self._add(self.fk, table, cols)
        if len(cols) >= _WIDE_KEY_THRESHOLD:
            self._add(self.wide, table, cols)

    def _names(self, table: str) -> list[str]:
        names = [table]
        if table in self.renames:
            names.append(self.renames[table])
        return names

    def length_for(self, table: str, col: str) -> int | None:
        names = self._names(table)
        if not any(col in self.indexed.get(t, ()) for t in names):  # not indexed → keep TEXT
            return None
        wide = any(col in self.wide.get(t, ()) for t in names)
        fk = any(col in self.fk.get(t, ()) for t in names)
        return _WIDE_VARCHAR_LEN if (wide and not fk) else _VARCHAR_LEN


def _split_cols(raw: str) -> list[str]:
    """Split an index column list, dropping ASC/DESC direction and quoting."""
    out = []
    for part in raw.split(","):
        tok = part.strip().strip('`"').split()
        if tok:
            out.append(tok[0].strip('`"'))
    return out


_RENAME_TO = re.compile(
    r"(?i)ALTER\s+TABLE\s+[`\"]?(\w+)[`\"]?\s+RENAME\s+TO\s+[`\"]?(\w+)[`\"]?"
)


def build_index_map(text: str, imap: IndexMap) -> None:
    """Accumulate indexed/fk/wide column facts from one migration file into imap."""
    # CREATE-then-RENAME idiom: a column defined in `X_new` is later indexed on `X`.
    for m in _RENAME_TO.finditer(text):
        imap.renames[m.group(1)] = m.group(2)
    # CREATE TABLE blocks: inline + composite keys.
    for blk in re.finditer(r"(?is)CREATE\s+TABLE\b.*?\n\s*\)\s*;", text):
        body = blk.group(0)
        tm = _CREATE_TABLE_NAME.search(body)
        if not tm:
            continue
        table = tm.group(1)
        for ln in body.splitlines():
            inline = _COL_DEF.match(ln)
            if inline and _KEY_KEYWORDS.search(ln):
                imap.mark(table, [inline.group(1)], fk=bool(re.search(r"(?i)\bREFERENCES\b", ln)))
            for m in _COMPOSITE_KEY.finditer(ln):
                fk = bool(re.match(r"(?is)\s*FOREIGN\s+KEY", m.group(0)))
                imap.mark(table, _split_cols(m.group(1)), fk=fk)
    # Standalone CREATE [UNIQUE] INDEX name ON table(cols).
    for m in _CREATE_INDEX.finditer(text):
        imap.index_table[m.group(1)] = m.group(2)
        imap.mark(m.group(2), _split_cols(m.group(3)))
    # ALTER TABLE ... ADD (UNIQUE|INDEX|FOREIGN KEY|...) (cols).
    for m in _ALTER_ADD_INDEX.finditer(text):
        fk = bool(re.search(r"(?i)FOREIGN\s+KEY", m.group(0)))
        imap.mark(m.group(1), _split_cols(m.group(2)), fk=fk)
    # ALTER TABLE ... ADD COLUMN <col> TEXT ... REFERENCES (inline FK).
    for m in _ALTER_ADD_FK.finditer(text):
        imap.mark(m.group(1), [m.group(2)], fk=True)


# The optional `ON CONFLICT DO NOTHING` tail absorbs a sqloader 0.2.15 convert defect: when a
# SQLite file opens with `BEGIN;` immediately followed by an `INSERT OR IGNORE`, the converter can
# mis-attach that INSERT's idempotency clause onto the BEGIN, emitting `BEGIN ON CONFLICT DO
# NOTHING;` (B0095, migration 047 — a syntax error on PostgreSQL). It is the same mis-attachment
# class the PRAGMA step documents, and a duplicate of the real INSERT's own clause, so dropping the
# whole transaction-control line is both required (BEGIN/COMMIT are stripped anyway, the migrator
# wraps each file in its own transaction) and lossless.
_TXN_CONTROL = re.compile(
    r"^\s*(?:(?:BEGIN|START)\s+TRANSACTION|BEGIN|(?:COMMIT|END)(?:\s+TRANSACTION)?)"
    r"(?:\s+ON\s+CONFLICT\s+DO\s+NOTHING)?\s*;\s*$",
    re.IGNORECASE,
)


_FUNC_DEFAULT = re.compile(
    r"\s+DEFAULT\s*\(\s*(?:strftime|datetime)\s*\([^)]*\)\s*\)"
    r"|\s+DEFAULT\s+(?:strftime|datetime)\s*\([^)]*\)",
    re.IGNORECASE,
)


_NOW_FUNC = re.compile(
    r"(?i)strftime\s*\(\s*'[^']*'\s*,\s*'now'\s*\)|datetime\s*\(\s*'now'\s*\)"
)
_NOW_EXPR = {
    # ISO-8601 UTC string, matching the application's now_iso() shape (no sub-second part).
    "mysql": "DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%sZ')",
    "postgres": "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')",
}


def replace_now_funcs(text: str, dialect: str) -> str:
    """Replace SQLite now-functions used as *values* with a dialect ISO-8601 expression.

    Migrations backfill created_at/updated_at with strftime('…','now') / datetime('now').
    Neither exists on MySQL/PostgreSQL; substitute a native expression producing the same
    ISO-8601 UTC string shape. (DEFAULT-clause occurrences are removed by strip_func_defaults.)
    """
    expr = _NOW_EXPR[dialect]
    return _NOW_FUNC.sub(lambda _m: expr, text)


def strip_func_defaults(text: str) -> str:
    """Remove SQLite function column DEFAULTs (strftime/datetime) for non-SQLite targets.

    Neither MySQL/MariaDB nor PostgreSQL accept arbitrary functions like
    strftime('…','now') in a DEFAULT clause on a TEXT column. The application always
    supplies these created_at/updated_at values explicitly (db.connection.now_iso), so the
    DEFAULT was only an unused SQLite-side safety net — dropping the clause (keeping NOT NULL)
    is portable and behaviour-preserving.
    """
    return _FUNC_DEFAULT.sub("", text)


_PG_CREATE_VIEW = re.compile(r"(?i)\bCREATE\s+VIEW\s+IF\s+NOT\s+EXISTS\b")


def fix_pg_create_view(text: str) -> str:
    """PostgreSQL has no CREATE VIEW IF NOT EXISTS; use the idempotent CREATE OR REPLACE VIEW."""
    return _PG_CREATE_VIEW.sub("CREATE OR REPLACE VIEW", text)


# SQLite scalar json_extract(col,'$.k') is converted by sqloader to PostgreSQL col->>'k'.
# But PostgreSQL's -> / ->> operators are defined only when the left operand is json/jsonb;
# our `meta` (and any JSON-bearing) column is declared TEXT, so `text ->> 'k'` raises
# "operator does not exist: text ->> unknown" and aborts the migration (B0095 / group 0095).
# Cast the left operand to jsonb. Matches `col->>'k'` and `tbl.col->'k'`; idempotent (a left
# operand already produced by a `::jsonb` cast is preceded by ':' and is skipped).
_PG_JSON_ARROW = re.compile(r"(?i)\b(\w+(?:\.\w+)?)\s*(->>?)\s*('(?:[^']|'')*')")


def fix_pg_json_text_ops(text: str) -> str:
    """Cast the left operand of a PostgreSQL ->/->> JSON access to jsonb (TEXT column safe)."""
    def repl(m: "re.Match") -> str:
        start = m.start(1)
        # Already part of a `::jsonb`/`::json` cast (e.g. a re-run) → leave untouched.
        if start > 0 and text[start - 1] == ":":
            return m.group(0)
        return f"{m.group(1)}::jsonb {m.group(2)} {m.group(3)}"
    return _PG_JSON_ARROW.sub(repl, text)


# SQLite/MySQL variadic json_array(...) / json_object(k,v,...) are passed through by sqloader
# verbatim, but PostgreSQL spells these json_build_array(...) / json_build_object(k,v,...).
# Left verbatim they fail at parse/plan time on PostgreSQL even when the UPDATE matches 0 rows
# (B0095, migration 031 — the "moving error" that surfaces once the ->> view defect is fixed).
_PG_JSON_CTOR_NAME = re.compile(r"(?i)\bjson_(array|object)\s*\(")
# An UPDATE backfill assigns the constructed json to a TEXT column; PostgreSQL has no
# assignment cast json→text, so the SET value must be cast ::text. Scope to one statement
# ([^;]) up to the WHERE/terminating ';'.
_PG_JSON_SET_ASSIGN = re.compile(
    r"(?is)(\bSET\s+\w+\s*=\s*)(json_build_(?:array|object)\b[^;]*?)(\s*(?:WHERE\b|;))"
)


def fix_pg_json_constructors(text: str) -> str:
    """Translate SQLite/MySQL json_array/json_object to PostgreSQL json_build_* and cast SET→text."""
    text = _PG_JSON_CTOR_NAME.sub(lambda m: f"json_build_{m.group(1).lower()}(", text)
    return _PG_JSON_SET_ASSIGN.sub(lambda m: f"{m.group(1)}({m.group(2)})::text{m.group(3)}", text)


# PostgreSQL extends the SQL GROUP BY functional-dependency relaxation ONLY to a table's
# PRIMARY KEY, never to a merely UNIQUE column. The v_tv_progress view (001, recreated in 027)
# groups by `d.doc_id` while selecting other bare d.* columns (d.project_id, d.module, ...).
# In documents, `doc_id` is UNIQUE NOT NULL but the primary key is the SERIAL `id`; SQLite
# allows the bare columns unconditionally and MySQL extends the relaxation to UNIQUE NOT NULL
# columns, so both accept it, but PostgreSQL aborts the migration with
# "column \"d.project_id\" must appear in the GROUP BY clause or be used in an aggregate
# function" (B0095 — the error that only surfaces once the ->> jsonb fix lets the view body
# parse). Group by the real primary key `id` instead: it is 1:1 with doc_id (identical groups,
# same aggregation) and makes every d.* column functionally dependent, validating the whole
# SELECT list. Idempotent: a rewritten `GROUP BY d.id` no longer matches.
_PG_GROUPBY_DOC_ID = re.compile(r"(?i)\bGROUP\s+BY\s+(\w+)\.doc_id\b")


def fix_pg_groupby_pk(text: str) -> str:
    """Rewrite GROUP BY <alias>.doc_id to GROUP BY <alias>.id (documents' real primary key).

    Scoped to `doc_id`: the only literal `doc_id` column grouped on in the migration set is
    documents.doc_id (UNIQUE NOT NULL, 1:1 with the PK id), so swapping the grouping key is
    semantics-preserving and unblocks PostgreSQL's functional-dependency check. The
    _PG_GROUPBY_NONPK regen guard fails loudly if a future view groups on a non-PK column the
    rewrite does not cover.
    """
    return _PG_GROUPBY_DOC_ID.sub(lambda m: f"GROUP BY {m.group(1)}.id", text)


# The SQLite "drop & recreate a table to alter it" idiom (003 groups, plus the _new+RENAME
# variant used by 023/024/025/027/033/039/044) does a bare ``DROP TABLE x``. SQLite allows it
# with foreign_keys OFF; MySQL is fenced by fix_mysql_fk_during_recreate. PostgreSQL refuses to
# drop a table still referenced by a FOREIGN KEY ("cannot drop table x because other objects
# depend on it … Use DROP … CASCADE", B0095, migration 003 — surfaces once the ->>/GROUP BY view
# fixes let the chain reach 003). DROP … CASCADE is wrong here: it would silently drop the
# dependents' FK constraints and never restore them, leaving the recreated table with weaker
# integrity than the SQLite/MySQL targets. Instead, fence each non-temp DROP TABLE with a pair of
# DO blocks that snapshot the inbound FKs from the catalog, drop them so the rebuild can proceed,
# and re-add them verbatim (original name + full pg_get_constraintdef, incl. ON DELETE / composite
# keys) after every table has been recreated. The recreated table keeps its original name in both
# idioms, so the saved "REFERENCES <name>" statements re-resolve. Views that depend on the table
# are dropped/recreated by the migration itself (e.g. 027), so only FKs are at stake here.
#
# Implementation notes that keep this invisible to the other passes:
#   * Temp tables are named `_fk_rb_<table>` (leading underscore) so _PG_DROP_TABLE_STMT — which
#     only matches a *non*-underscore table — never treats the fence's own bookkeeping as a drop.
#   * The snapshot is a CREATE TEMP TABLE … AS SELECT (CTAS), never an INSERT, so check_lossless's
#     INSERT-count parity is untouched.
#   * ON COMMIT DROP cleans the temp table at the migrator's per-file transaction boundary.
#   * Self-referential FKs (conrelid = confrelid) are excluded: the recreate body re-declares them
#     inline, so re-adding the saved copy would duplicate them.
# A table with no inbound FK (id_counter / answers / the tokens_before_* backups) snapshots zero
# rows and the fence is a harmless no-op, so the rule "fence every non-temp DROP TABLE" is uniform.
_PG_DROP_TABLE_STMT = re.compile(
    r"(?im)^[ \t]*DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?([A-Za-z]\w*)\s*;[ \t]*$"
)
_PG_FK_REBUILD_TAG = "[pg-fk-rebuild]"


def _pg_fk_snapshot_block(table: str) -> str:
    """DO block: snapshot inbound FKs of <table> into a temp, then drop them (pre-DROP TABLE)."""
    tmp = f"_fk_rb_{table}"
    sel = (
        "            SELECT 'ALTER TABLE ' || quote_ident(n.nspname) || '.' "
        "|| quote_ident(c.relname)\n"
        "                   || ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' "
        "|| pg_get_constraintdef(con.oid) AS stmt\n"
        "            FROM pg_constraint con\n"
        "            JOIN pg_class c ON c.oid = con.conrelid\n"
        "            JOIN pg_namespace n ON n.oid = c.relnamespace\n"
        f"            WHERE con.contype = 'f' AND con.confrelid = to_regclass('{table}')\n"
        "              AND con.conrelid <> con.confrelid"
    )
    return (
        f'-- {_PG_FK_REBUILD_TAG} preserve inbound FOREIGN KEYs across the drop+recreate of "{table}"\n'
        "DO $$\n"
        "DECLARE _stmt text;\n"
        "BEGIN\n"
        f"    CREATE TEMP TABLE {tmp} ON COMMIT DROP AS\n"
        f"{sel};\n"
        "    FOR _stmt IN\n"
        "        SELECT 'ALTER TABLE ' || quote_ident(n.nspname) || '.' || quote_ident(c.relname)\n"
        "               || ' DROP CONSTRAINT ' || quote_ident(con.conname)\n"
        "        FROM pg_constraint con\n"
        "        JOIN pg_class c ON c.oid = con.conrelid\n"
        "        JOIN pg_namespace n ON n.oid = c.relnamespace\n"
        f"        WHERE con.contype = 'f' AND con.confrelid = to_regclass('{table}')\n"
        "          AND con.conrelid <> con.confrelid\n"
        "    LOOP\n"
        "        EXECUTE _stmt;\n"
        "    END LOOP;\n"
        "END $$;\n"
    )


def _pg_fk_restore_block(table: str) -> str:
    """DO block: re-add the snapshotted inbound FKs of <table> (appended after all recreates)."""
    tmp = f"_fk_rb_{table}"
    return (
        f'-- {_PG_FK_REBUILD_TAG} restore inbound FOREIGN KEYs for "{table}"\n'
        "DO $$\n"
        "DECLARE _stmt text;\n"
        "BEGIN\n"
        f"    IF to_regclass('pg_temp.{tmp}') IS NOT NULL THEN\n"
        f"        FOR _stmt IN SELECT stmt FROM {tmp} LOOP\n"
        "            EXECUTE _stmt;\n"
        "        END LOOP;\n"
        "    END IF;\n"
        "END $$;\n"
    )


def fix_pg_table_rebuild(text: str) -> str:
    """Fence every non-temp DROP TABLE so PostgreSQL can drop & recreate FK-referenced tables.

    Snapshots and re-adds the inbound foreign keys around the drop (see the module-level note).
    Idempotent: a file already carrying the fence tag is returned unchanged.
    """
    if _PG_FK_REBUILD_TAG in text:
        return text
    tables: list[str] = []

    def repl(m: "re.Match") -> str:
        table = m.group(1)
        if table not in tables:
            tables.append(table)
        return _pg_fk_snapshot_block(table) + m.group(0)

    rewritten = _PG_DROP_TABLE_STMT.sub(repl, text)
    if not tables:
        return text
    if not rewritten.endswith("\n"):
        rewritten += "\n"
    restore = "\n".join(_pg_fk_restore_block(t) for t in tables)
    return rewritten + "\n" + restore


def pg_unfenced_drop_table(text: str) -> str | None:
    """Return the first non-temp table dropped without an FK fence above it, else None."""
    for m in _PG_DROP_TABLE_STMT.finditer(text):
        sentinel = (
            f'{_PG_FK_REBUILD_TAG} preserve inbound FOREIGN KEYs across '
            f'the drop+recreate of "{m.group(1)}"'
        )
        if sentinel not in text[: m.start()]:
            return m.group(1)
    return None


# SQLite's INSERT OR IGNORE (and MySQL's INSERT IGNORE) skip a row that violates ANY constraint —
# UNIQUE, NOT NULL, FOREIGN KEY, and CHECK. sqloader converts INSERT OR IGNORE to PostgreSQL's
# `... ON CONFLICT DO NOTHING`, but ON CONFLICT only swallows UNIQUE/exclusion conflicts: a CHECK
# (or NOT NULL / FK) violation still aborts the statement. That diverges on migration 015, which
# `INSERT OR IGNORE`s document_types rows with series='qna' — a value the series CHECK never admits
# on any backend, so SQLite/MySQL silently drop those rows while PostgreSQL errors out (B0095). Wrap
# each converted OR-IGNORE insert in a plpgsql block that swallows exactly the violations OR IGNORE
# swallows, restoring "ignore on any constraint" parity. The inner ON CONFLICT DO NOTHING is kept so
# UNIQUE idempotency still works per-row; the EXCEPTION subtransaction covers the rest.
#
# Faithfulness caveat: the EXCEPTION rolls back the whole INSERT, so a *multi-row VALUES* insert
# where SQLite would keep the valid rows and drop only the violating ones would here drop them all.
# The current set has no such case — the only CHECK-violating OR-IGNORE insert (015) has every row
# violating, so statement-level and row-level skip are identical. The tempered `(?!INSERT)` body
# keeps each match scoped to a single insert (it never spans a following statement). A plain INSERT
# (no ON CONFLICT, i.e. not OR IGNORE) is left fail-loud, as on SQLite.
_PG_OR_IGNORE_TAG = "$fg_or_ignore$"
_PG_OR_IGNORE_INSERT = re.compile(
    r"(?ims)^([ \t]*)(INSERT\b(?:(?!\bINSERT\b).)*?\bON\s+CONFLICT\s+DO\s+NOTHING\s*;)"
)


def fix_pg_or_ignore_swallow(text: str) -> str:
    """Wrap each converted OR-IGNORE insert so PostgreSQL skips CHECK/NOT NULL/FK violators too.

    Idempotent: a file already carrying the wrapper tag is returned unchanged.
    """
    if _PG_OR_IGNORE_TAG in text:
        return text

    def repl(m: "re.Match") -> str:
        indent, stmt = m.group(1), m.group(2)
        return (
            f"{indent}DO {_PG_OR_IGNORE_TAG}\n"
            f"{indent}BEGIN\n"
            f"{indent}{stmt}\n"
            f"{indent}EXCEPTION WHEN check_violation OR not_null_violation "
            f"OR foreign_key_violation THEN\n"
            f"{indent}    NULL;  -- OR IGNORE: drop the violating row(s), like SQLite/MySQL\n"
            f"{indent}END {_PG_OR_IGNORE_TAG};"
        )

    return _PG_OR_IGNORE_INSERT.sub(repl, text)


def strip_txn_control(text: str) -> str:
    """Drop standalone BEGIN/COMMIT/END TRANSACTION lines (non-SQLite targets).

    The migrator already runs each migration file inside a single transaction
    (migrator.apply_migration → begin_transaction), so the SQLite-authored explicit
    BEGIN TRANSACTION; ... COMMIT; wrappers are redundant. On MySQL/MariaDB
    'BEGIN TRANSACTION' is a syntax error, and a mid-file COMMIT would break the
    migrator's atomic wrap. Removing these lines keeps each file atomic.
    """
    return "\n".join(
        ln for ln in text.splitlines() if not _TXN_CONTROL.match(ln)
    ) + ("\n" if text.endswith("\n") else "")


def fix_mysql_fk_during_recreate(text: str) -> str:
    """Allow the SQLite 'drop & recreate table to alter a CHECK' idiom on MySQL/MariaDB.

    MySQL/MariaDB refuse to DROP a table still referenced by a foreign key (error 1451),
    whereas SQLite allows it with foreign_keys OFF (these migrations even say "foreign keys
    must be disabled"). Wrap any migration that drops a table in a FOREIGN_KEY_CHECKS=0/1
    fence so the drop+recreate+restore proceeds; the recreated table keeps the same name
    and key columns, so the dependent FKs reconnect. On a fresh DB the tables are empty, so
    no row-level FK/CHECK validation is at stake.
    """
    if not re.search(r"(?im)^\s*DROP\s+TABLE\b", text):
        return text
    return "SET FOREIGN_KEY_CHECKS=0;\n" + text.rstrip() + "\nSET FOREIGN_KEY_CHECKS=1;\n"


def _promote_text(line: str, length: int) -> str:
    """Replace the first standalone TEXT type token on a column line with VARCHAR(n)."""
    return re.sub(r"(?i)\bTEXT\b", f"VARCHAR({length})", line, count=1)


def fix_mysql_text_keys(text: str, imap: IndexMap) -> str:
    """Promote every indexed TEXT column to VARCHAR for MySQL/MariaDB (step 3, MySQL-only).

    MySQL/MariaDB cannot index a TEXT column without a prefix length, so any TEXT column
    that participates in a key OR a secondary index must become VARCHAR. The (table, column)
    facts are precomputed across the whole migration set (build_index_map), because a column
    defined in 001 may be indexed by a later migration.
    """
    lines = text.splitlines(keepends=True)
    n = len(lines)

    # Rewrite TEXT column definitions inside CREATE TABLE blocks.
    i = 0
    while i < n:
        tm = _CREATE_TABLE_NAME.search(lines[i]) if _CREATE_TABLE.search(lines[i]) else None
        if tm:
            table = tm.group(1)
            depth = 0
            j = i
            while j < n:
                cm = _COL_DEF.match(lines[j])
                if cm:
                    length = imap.length_for(table, cm.group(1))
                    if length is not None:
                        lines[j] = _promote_text(lines[j], length)
                depth += lines[j].count("(") - lines[j].count(")")
                if j > i and depth <= 0 and lines[j].rstrip().endswith(";"):
                    break
                j += 1
            i = j + 1
        else:
            i += 1

    text = "".join(lines)

    # ALTER TABLE <table> ADD COLUMN <col> TEXT ... (single- or multi-line, incl. inline FK).
    def _alter_repl(m: "re.Match") -> str:
        length = imap.length_for(m.group(2), m.group(3))
        if length is None:
            return m.group(0)
        return f"{m.group(1)}VARCHAR({length})"

    return _ALTER_ADD_COL.sub(_alter_repl, text)


def fix_mysql_drop_index(text: str, imap: IndexMap) -> str:
    """Add the required ``ON <table>`` to bare ``DROP INDEX [IF EXISTS] name;`` for MySQL.

    SQLite identifies indexes globally (DROP INDEX name); MySQL/MariaDB require the table
    (DROP INDEX name ON table). The owning table is recovered from the CREATE INDEX seen
    earlier in the migration set.
    """
    def repl(m: "re.Match") -> str:
        ine, name, on = m.group(1) or "", m.group(2), m.group(3)
        if on:  # already qualified
            return m.group(0)
        table = imap.index_table.get(name)
        if not table:
            return m.group(0)
        return f"DROP INDEX {ine}{name} ON {table};"

    return _DROP_INDEX.sub(repl, text)


def _insert_chunks(text: str) -> list[str]:
    """Split into chunks each starting at an INSERT keyword (comment-stripped).

    Used by the lossless check. Splitting on ';' is unsafe here because seed
    bodies (045) embed ';' inside string literals; INSERT-keyword boundaries are.
    """
    text = "\n".join(re.sub(r"--.*$", "", ln) for ln in text.splitlines())
    starts = [m.start() for m in _INSERT_HEAD.finditer(text)]
    return [text[s:(starts[i + 1] if i + 1 < len(starts) else len(text))]
            for i, s in enumerate(starts)]


def check_lossless(src_text: str, out_text: str, dialect: str) -> list[str]:
    """Return a list of problems; empty means conflict handling is preserved."""
    s = _insert_chunks(src_text)
    d = _insert_chunks(out_text)
    s_idem = [c for c in s if re.match(r"(?is)\s*INSERT\s+OR\s+IGNORE", c)]
    if dialect == "mysql":
        d_idem = [c for c in d
                  if re.match(r"(?is)\s*INSERT\s+IGNORE", c) or re.search(r"(?i)ON\s+DUPLICATE", c)]
    else:
        d_idem = [c for c in d if re.search(r"(?i)ON\s+CONFLICT", c)]
    problems = []
    if len(s) != len(d):
        problems.append(f"INSERT count: sqlite={len(s)} {dialect}={len(d)}")
    if len(s_idem) != len(d_idem):
        problems.append(f"idempotent INSERT: sqlite={len(s_idem)} {dialect}={len(d_idem)}")
    return problems


def regenerate(verify_only: bool) -> int:
    if not os.path.isdir(SRC):
        print(f"!! sqlite source not found: {SRC}", file=sys.stderr)
        return 2

    tmp_root = tempfile.mkdtemp(prefix="wf_dialect_")
    rc = 0
    try:
        for out_name, to_value in TARGETS:
            raw_dir = os.path.join(tmp_root, out_name)
            os.makedirs(raw_dir, exist_ok=True)
            subprocess.run(
                [sys.executable, "-m", "sqloader", "convert",
                 "--from", "sqlite", "--to", to_value,
                 "--path", SRC, "--out", raw_dir],
                check=True, cwd=SERVER,
            )
            dest = os.path.join(MIG, out_name)
            os.makedirs(dest, exist_ok=True)

            fnames = sorted(os.listdir(raw_dir))
            # Pre-process: strip PRAGMA (+ MySQL partial-index emulation) for every file.
            staged: dict[str, str] = {}
            for fname in fnames:
                raw = open(os.path.join(raw_dir, fname), encoding="utf-8").read()
                final = strip_pragma(raw)
                # The migrator wraps each file in its own transaction; the SQLite-authored
                # BEGIN/COMMIT wrappers are redundant and break MySQL. Strip for non-SQLite.
                final = strip_txn_control(final)
                final = strip_func_defaults(final)
                final = replace_now_funcs(final, out_name)
                if out_name == "postgres":
                    final = fix_pg_create_view(final)
                    final = fix_pg_json_text_ops(final)
                    final = fix_pg_json_constructors(final)
                    final = fix_pg_groupby_pk(final)
                    final = fix_pg_table_rebuild(final)
                    final = fix_pg_or_ignore_swallow(final)
                if out_name == "mysql":
                    final = fix_mysql_partial_indexes(final)
                    final = fix_mysql_nonunique_partial_indexes(final)
                    final = fix_mysql_fk_during_recreate(final)
                # Code-handled migrations (B0091): replace the converter's broken
                # output with a documented no-op stub on non-SQLite targets.
                if _migration_id(fname) in _CODE_HANDLED_IDS:
                    final = _NOOP_STUB.format(fname=fname, target=out_name)
                staged[fname] = final

            # MySQL needs a migration-set-wide view of which columns are indexed before
            # promoting TEXT→VARCHAR, since a column defined in 001 can be indexed later.
            if out_name == "mysql":
                imap = IndexMap()
                for fname in fnames:
                    build_index_map(staged[fname], imap)
                for fname in fnames:
                    staged[fname] = fix_mysql_text_keys(staged[fname], imap)
                    staged[fname] = fix_mysql_drop_index(staged[fname], imap)

            for fname in fnames:
                src_text = open(os.path.join(SRC, fname), encoding="utf-8").read()
                final = staged[fname]

                # B0091 guard: any non-code-handled file still carrying SQLite-only
                # JSON DML on a non-SQLite target would ship broken and abort startup.
                if _migration_id(fname) not in _CODE_HANDLED_IDS and _UNSUPPORTED_DML.search(final):
                    rc = 1
                    print(
                        f"!! UNSUPPORTED DML {out_name}/{fname}: SQLite-only JSON DML "
                        f"(json_each/json_group_array/json_array_length) does not translate; "
                        f"move the transform to a Python backfill and add "
                        f"'{_migration_id(fname)}' to _CODE_HANDLED_IDS.",
                        file=sys.stderr,
                    )

                # B0091 (041): a CREATE TRIGGER / RAISE() that survives to a
                # non-SQLite target is untranslatable procedural SQL and aborts
                # startup with a 1064 parse error. Fail loudly rather than ship it.
                if _migration_id(fname) not in _CODE_HANDLED_IDS and _UNSUPPORTED_TRIGGER.search(final):
                    rc = 1
                    print(
                        f"!! UNSUPPORTED TRIGGER {out_name}/{fname}: SQLite-only CREATE "
                        f"TRIGGER / RAISE() does not translate to {out_name}; re-express the "
                        f"invariant as a portable CHECK (preferred) or author the dialect "
                        f"trigger by hand. Do NOT ship the verbatim SQLite trigger.",
                        file=sys.stderr,
                    )

                # B0095 guard: a PostgreSQL file must not ship an uncast ->/->> access or a
                # verbatim SQLite/MySQL json_array/json_object constructor (both abort startup).
                if out_name == "postgres":
                    if _PG_UNCAST_ARROW.search(final):
                        rc = 1
                        print(
                            f"!! UNCAST JSON ARROW {out_name}/{fname}: a ->/->> access lacks a "
                            f"::jsonb cast on its left operand (PostgreSQL has no text->>text "
                            f"operator). Extend fix_pg_json_text_ops.",
                            file=sys.stderr,
                        )
                    if _PG_SQLITE_JSON_CTOR.search(final):
                        rc = 1
                        print(
                            f"!! SQLITE JSON CTOR {out_name}/{fname}: json_array(/json_object( is "
                            f"not PostgreSQL syntax (use json_build_array/json_build_object). "
                            f"Extend fix_pg_json_constructors.",
                            file=sys.stderr,
                        )
                    if _PG_GROUPBY_NONPK.search(final):
                        rc = 1
                        print(
                            f"!! GROUP BY NON-PK {out_name}/{fname}: GROUP BY <alias>.doc_id "
                            f"groups on a UNIQUE (non-PRIMARY-KEY) column, which PostgreSQL "
                            f"rejects ('must appear in the GROUP BY clause'). Extend "
                            f"fix_pg_groupby_pk.",
                            file=sys.stderr,
                        )
                    unfenced = pg_unfenced_drop_table(final)
                    if unfenced:
                        rc = 1
                        print(
                            f"!! UNFENCED DROP TABLE {out_name}/{fname}: 'DROP TABLE {unfenced}' "
                            f"is not wrapped in the inbound-FK snapshot/restore fence, so "
                            f"PostgreSQL aborts if any FK references it ('cannot drop table … "
                            f"because other objects depend on it'). Extend fix_pg_table_rebuild.",
                            file=sys.stderr,
                        )

                problems = check_lossless(src_text, final, out_name)
                if problems:
                    rc = 1
                    for p in problems:
                        print(f"!! LOSSY {out_name}/{fname}: {p}", file=sys.stderr)

                dpath = os.path.join(dest, fname)
                if verify_only:
                    cur = open(dpath, encoding="utf-8").read() if os.path.exists(dpath) else None
                    if cur != final:
                        rc = 1
                        print(f"~~ DIFF {out_name}/{fname} (committed != regenerated)")
                else:
                    with open(dpath, "w", encoding="utf-8") as f:
                        f.write(final)

            print(f"{'verified' if verify_only else 'wrote'} {out_name}: "
                  f"{len(os.listdir(raw_dir))} file(s)")
    finally:
        shutil.rmtree(tmp_root, ignore_errors=True)

    if rc == 0:
        print("OK: lossless and "
              + ("in sync." if verify_only else "regenerated."))
    return rc


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verify", action="store_true",
                    help="regenerate to temp and diff against committed; do not write")
    args = ap.parse_args()
    return regenerate(args.verify)


if __name__ == "__main__":
    raise SystemExit(main())
