-- 037_rejection_id_backfill.sql  (mysql — intentional no-op, generated by regen_dialect_migrations.py)
--
-- The data transform for this migration is handled by portable Python at
-- startup (server/modules/flow_gate/db/backfills/) because the SQLite source
-- uses JSON DML that does not translate to this backend (B0091). Kept as a
-- documented no-op so the migration ledger stays unbroken.
SELECT 1;
