CREATE TABLE IF NOT EXISTS tr2_approval_attempts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    attempt_id VARCHAR(64) NOT NULL UNIQUE,
    request_key VARCHAR(64) UNIQUE,
    tr2_doc_id VARCHAR(191) NOT NULL,
    project_id VARCHAR(191) NOT NULL,
    group_id VARCHAR(191) NOT NULL,
    document_revision INTEGER NOT NULL,
    document_etag TEXT,
    approval_round INTEGER NOT NULL,
    actor_user_id VARCHAR(191) NOT NULL,
    spec_fingerprint VARCHAR(64) NOT NULL,
    baseline_fingerprint VARCHAR(71) NOT NULL,
    live_fingerprint VARCHAR(71),
    state VARCHAR(32) NOT NULL,
    phase VARCHAR(32) NOT NULL,
    result_code VARCHAR(64),
    error_code VARCHAR(64),
    error_detail TEXT,
    precheck_json TEXT,
    apply_json TEXT,
    validation_json TEXT,
    commit_json TEXT,
    ledger_json TEXT,
    backup_bundle_id VARCHAR(64),
    pre_apply_head_sha VARCHAR(40),
    commit_sha VARCHAR(40),
    ledger_row_id INT,
    started_at TEXT NOT NULL,
    heartbeat_at VARCHAR(64) NOT NULL,
    finished_at TEXT,
    updated_at TEXT NOT NULL,
    KEY idx_tr2_attempt_doc (tr2_doc_id, id),
    KEY idx_tr2_attempt_group_state (group_id, state),
    KEY idx_tr2_attempt_stale (state, heartbeat_at),
    CONSTRAINT fk_tr2_attempt_document FOREIGN KEY (tr2_doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE,
    CONSTRAINT fk_tr2_attempt_ledger FOREIGN KEY (ledger_row_id) REFERENCES tr_commit_ledger(id)
);
