"""The `ai_invoke_service` public surface, assembled from this package.

0501 NR0003 §20: external production code and a large number of existing tests import
`modules.flow_gate.services.ai_invoke_service` and reach through it -- including for
private names they monkeypatch. Moving the implementation into a package must not move
that contract, so `ai_invoke_service.py` stays exactly where it was and re-exports this
module; this module is the one place that says, name by name, which module of the
package each of those names actually comes from.

There is no wrapper, no `__getattr__`, and no dynamic lookup here: every line below is a
plain `from .<owner> import <name>`, so `ai_invoke_service.<name>` has one grep-able
definition site and go-to-definition reaches the real function in two hops. `__all__` is
the complete inventory of the surface, and it is what `ai_invoke_service.py`'s star
import re-exports.

This module is a LEAF of the package in the other direction: nothing inside `ai_invoke/`
imports it, and nothing inside `ai_invoke/` imports `ai_invoke_service` at module level
(the seams go through `_svc()`, resolved at call time). That is what lets a fresh
interpreter enter the graph at any one of these modules -- including this one -- and
still finish loading.
"""

from __future__ import annotations

# runtime.py — parameters, run registry, scratch, run-scoped text bookkeeping
from .runtime import (
    ANTHROPIC_VERSION,
    API_CALL_MAX_TIMEOUT_SEC,
    API_MAX_TOKENS,
    API_MAX_TOOL_NUDGES,
    API_MAX_TURNS_PER_DOC,
    CHAIN_MEMBER_HOP_KINDS,
    CONCURRENT_RUNS_PER_GROUP,
    ENGINE_NOTIFY_STOP_CODES,
    FAST_FAIL_WINDOW_SEC,
    HOP_HANDOFF_FAILED_STOP_CODE,
    HOP_HANDOFF_GRACE_SEC,
    HOP_HANDOFF_INTERRUPTED_STOP_CODE,
    HOP_HANDOFF_STOP_CODE,
    HOP_TIMEOUT_SEC,
    INBOX_NOTIFY_STOP_CODES,
    LAST_MESSAGE_EXCERPT_BYTES,
    LAST_MESSAGE_MAX_BYTES,
    NOTIFY_STOP_CODES,
    NO_OUTPUT_MAX_ATTEMPTS,
    ORACLE_SETTLE_SEC,
    OUTPUT_TAIL_BYTES,
    PARK_NOTIFY_STOP_CODES,
    PROVIDER_UNAVAILABLE_CODE,
    PROVIDER_UNAVAILABLE_MESSAGE,
    RESTART_MAX_ATTEMPTS_DEFAULT,
    RESUMABLE_STOP_CODES,
    RETRY_MIN_REMAINING_SEC,
    REVIEW_CAP_REACHED_STOP_CODE,
    REVIEW_COUNT_DEFAULT,
    REVIEW_EXHAUSTED_STOP_CODE,
    REVIEW_HOP_KIND,
    REVIEW_NO_VERDICT_STOP_CODE,
    REVIEW_REASON_MAX_CHARS,
    REVIEW_REASON_MAX_FINDINGS,
    REVIEW_REJECT_DENIED_STOP_CODE,
    REVIEW_REJECT_FAILED_STOP_CODE,
    REVIEW_ROUNDS_NO_LIMIT,
    REVIEW_STALLED_STOP_CODE,
    REVIEW_STALL_ROUNDS,
    REVIEW_STOP_CODES,
    REVIEW_VERDICTS,
    REVIEW_VERDICT_HOLD_STOP_CODE,
    REWORK_HOP_KIND,
    RUN_LIST_LIMIT_DEFAULT,
    RUN_LIST_LIMIT_MAX,
    RUN_TIMEOUT_BASE_SEC,
    RUN_TIMEOUT_CAP_SEC,
    SCRATCH_MANIFEST_NAME,
    SCRATCH_MANIFEST_SCHEMA,
    SCRATCH_RETENTION_DAYS,
    SOURCE_DIRTY_FILES_LIMIT,
    STALL_POLL_INTERVAL_SEC,
    STALL_WATCHDOG_JOIN_SEC,
    STEP_TIMEOUT_MAX_SEC,
    STEP_TIMEOUT_MIN_SEC,
    WORK_HOP_KIND,
    _AUTH_HEADER_RE,
    _BEARER_TOKEN_RE,
    _CHAT_TOOL_DESC,
    _CHAT_TOOL_NAME,
    _CHAT_TOOL_SCHEMA,
    _DECIDE_TOOL_DESC,
    _DECIDE_TOOL_NAME,
    _DECIDE_TOOL_SCHEMA,
    _PROMPT_ECHO_MIN_LEN,
    _REGISTER_TOOL_DESC,
    _REGISTER_TOOL_NAME,
    _REGISTER_TOOL_SCHEMA,
    _RESOLVE_TOOL_DESC,
    _RESOLVE_TOOL_NAME,
    _RESOLVE_TOOL_SCHEMA,
    _RUN_ID_RE,
    active_run_for_group as _active_run_for_group,
    _absolute_cap_sec,
    _absolute_remaining_sec,
    _atomic_write_manifest,
    _auto_resume,
    _auto_resume_lock,
    _cleanup_retained_scratches,
    _create_scratch,
    _delete_owned_scratch,
    group_resume_lock as _group_resume_lock,
    _group_resume_locks,
    _group_resume_locks_guard,
    _http_error,
    _is_reparse_or_symlink,
    _known_run_prompts,
    _known_run_raw_tokens,
    _manifest_for,
    _mark_scratch_completed,
    _next_run_id,
    _note_issued_prompt,
    _note_issued_raw_token,
    _project_scratch_root,
    _redact_secrets,
    _run_counter,
    _run_counter_floor_date,
    run_list_item_live as _run_list_item_live,
    _runs,
    _runs_lock,
    _safe_scratch_log,
    _sanitize_project_name,
    _validate_scratch_manifest,
    excerpt,
    get_run_record,
    is_run_live,
    list_live_runs,
    logger,
    prompt_digest,
    restart_max_attempts_choices,
)

# oracle.py — completion probes and pure helpers
from .oracle import (
    _SCOPE_PROBES,
    _git_status_paths,
    map_lookup as _map_lookup,
    normalize_ws as _normalize_ws,
    _oracle_doc_id,
    prioritize_chain as _prioritize_chain,
    _probe,
    _probe_base_dirty,
    _probe_conversation_head,
    _probe_doc_reviews,
    _probe_doc_revision,
    _probe_sequence_max_item,
    _probe_test_runs,
    _provider_brief,
    review_findings as _review_findings,
    _review_hop_recovery_open,
    _review_hop_recovery_run,
    review_key as _review_key,
    _scope_oracle,
    _scope_oracle_retry_open,
    _scope_oracle_retry_run,
    _uses_scope_oracle,
    _work_landed,
    review_finding_digest,
)

# admission.py — provider/lease/token policy and start_run
from .admission import (
    _INITIAL_SOURCE_SYNC_FAILED_COPY,
    _INITIAL_SYNC_SAFE_SKIP_REASONS,
    _RUN_ID_COLLISION_COPY,
    _WORKTREE_UNAVAILABLE_COPY,
    _call_issue_builder,
    _continuation_docs_target,
    _deadline_iso,
    _ensure_initial_source_sync,
    _hop_item_seq_or_none,
    _hop_worker_item_seq,
    _hop_worker_rows,
    _inject_hop_notes,
    _instruction_mode_fallback_applied,
    _is_group_worktree,
    _normalized_instruction_mode,
    _paired_report_row,
    _reclaim_orphan_lease_token,
    _record_orphaned_lease_run,
    _require_group_worktree,
    _resolve_continuation_hop_note,
    _resolve_continuation_hop_override,
    _resolve_continuation_hop_provider,
    _resolve_restart_max_attempts,
    _resolve_timeout_sec,
    _worker_source_kind,
    force_release_group_lease,
    list_runtime_providers,
    resolve_pinned_provider_name,
    resolve_stored_step_note,
    start_run,
    startup_recover_leases,
    stored_hop_provider,
)

# provider_api.py — HTTP/API transport
from .provider_api import (
    _api_help_prompt,
    _call_anthropic,
    _call_openai,
    _http_post_json,
    _resolve_agent_api_base,
    _resolve_transport_api_base,
    _sanitize_diagnostic_base,
)

# provider_cli.py — subprocess/CLI transport
from .provider_cli import (
    _canonicalize_cli_prompt,
    _claim_watchdog_kill,
    _cli_execute,
    _progress_watchdog_loop,
    _recover_cli_last_message,
    _resolve_cli_launch,
    _shell_kind,
    _start_progress_watchdog,
    _stop_progress_watchdog,
)

# worker.py — worker orchestration
from .worker import (
    _adopt_continuation_token,
    _api_bound_request,
    _api_execute,
    _api_read_document,
    _bind_register_context,
    _classify_end_reason,
    _conversation_context,
    _conversation_turn_register,
    _execute_provider_chain,
    _has_pending_question,
    _inbox_register,
    _no_output_detail,
    _now_mono,
    _oracle_new_docs,
    _prepare_retry_token,
    _register_envelope,
    _remaining_sec,
    _reset_attempt_state,
    _resolve_conflict,
    _retry_eligible,
    _retry_provider_chain,
    _retry_remaining_sec,
    _run_register_context,
    _stall_remaining_sec,
    _tool_result_msg,
    _worker,
    _workflow_decide,
)

# finalize.py — judging, stop records, persistence, finished payload
from .finalize import (
    LEASE_DENIAL_RECORD_LIMIT,
    _TIMEOUT_KINDS,
    _apply_stop_row,
    _finalize_run,
    _format_span,
    _judge_hop,
    _notify_chain_failure_if_needed,
    _persist_register_context_failures,
    _persist_run_record,
    _resolve_stop_code,
    _resolve_timeout_diagnostics,
    _settle_and_judge,
    _stop_reason_text,
    finished_payload,
    is_resumable,
    mark_chain_stop,
    mark_group_lease_denied,
    previous_timeout_handoff,
    stamp_chain_stop,
    stop_reason_text,
)

# chain.py — continuous chain, pause/resume, handoff
from .chain import (
    _broadcast,
    _clear_handoff_row,
    _handoff_bundle,
    _maybe_auto_resume_hop,
    _next_incomplete_item_seq,
    _open_q_doc_ids,
    _park_handoff,
    _paused_row_resume_state,
    _sequence_completion_state,
    _spawn_auto_resume,
    _write_handoff_row,
    active_all,
    cancel_run,
    clear_auto_resume,
    has_active_run,
    mark_user_paused,
    pause_run,
    peek_auto_resume,
    pop_auto_resume,
    release_paused_chain,
    request_auto_resume,
    resume_chain,
    startup_recover_handoffs,
)

# review.py — the review/rework gate
from .review import (
    REVIEW_LOCUS_UNSPECIFIED,
    REVIEW_PENDING_DOC_STATUSES,
    REVIEW_REJECT_HEADING,
    _append_engine_review_clause,
    _auto_reject,
    _checkpoint_document_review_loop,
    _insert_document_review_loop,
    _latest_review_of,
    _log_review_annotation_failure,
    _parse_rejection_history,
    _pending_review_slot,
    _provider_name_of,
    _restore_document_review_loop,
    _resumable_reviewer_overrides,
    _review_already_rejected,
    _settle_gate_pass,
    _spawn_review_hop,
    _spawn_rework_hop,
    active_review_selection,
    build_auto_reject_reason,
    build_document_review_loop_history,
    check_expected_progress,
    compute_review_baseline,
    document_review_loop_payload,
    resolve_document_review_loop_gate,
    resolve_loop_provider,
    resolve_review_count,
    resolve_review_gate,
    resolve_reviewer,
    resolve_round_limit,
    resolve_step_executor,
    review_rounds_remain,
    run_review_gate,
)

# diagnostics.py — run history and status read models
from .diagnostics import (
    _persisted_register_failures,
    _run_detail_from_row,
    _run_list_item_stored,
    ai_run_succeeded,
    get_active_status,
    get_run_detail,
    get_status,
    list_runs,
)

# Re-exported unchanged from outside the package: these were module-level
# imports of the pre-split ai_invoke_service.py, so they are part of the
# surface too (`ai_invoke_service.get_store` is monkeypatched by name).
from datetime import datetime, timedelta, timezone
from typing import Callable, Iterable, Optional
from modules.flow_gate.db.connection import get_store, now_iso
from modules.flow_gate.utils.api_key_crypto import ApiKeyCryptoError
from modules.flow_gate.services.git_service import GitServiceError
from fastapi import HTTPException
from pathlib import Path
from modules.flow_gate.settings import ai_execution_policy_service
from modules.flow_gate.settings import ai_settings_service
from modules.flow_gate.services import api_server_tools
from modules.flow_gate.db import conversation_turns as db_conversation_turns
from modules.flow_gate.db import documents as db_docs
from modules.flow_gate.db import git_integration as db_git
from modules.flow_gate.db import group_ai_leases as db_group_ai_leases
from modules.flow_gate.db import projects as db_projects
from modules.flow_gate.db import question_items as db_question_items
from modules.flow_gate.db import questions as db_questions
from modules.flow_gate.db import document_reviews as db_reviews
from modules.flow_gate.db import test_runs as db_test_runs
from modules.flow_gate.db import tokens as db_tokens
from modules.flow_gate.db import workflow_sequences as db_wfseq
from modules.flow_gate.services import git_service
import hashlib
from modules.flow_gate.services import invoke_mention_service
import json
import logging
import os
from modules.flow_gate.services import process_runner
from modules.flow_gate.services import q_service
import re
from modules.flow_gate.services import register_binding
import shutil
from modules.flow_gate.storage import paths as storage_paths
from modules.flow_gate import template_provision
import threading
import time
from modules.flow_gate.services import token_service
import urllib.error
import urllib.request

# The complete inventory of `ai_invoke_service.<name>`; the star import in
# ai_invoke_service.py re-exports exactly this list and nothing else.
__all__ = [
    "ANTHROPIC_VERSION",
    "API_CALL_MAX_TIMEOUT_SEC",
    "API_MAX_TOKENS",
    "API_MAX_TOOL_NUDGES",
    "API_MAX_TURNS_PER_DOC",
    "ApiKeyCryptoError",
    "CHAIN_MEMBER_HOP_KINDS",
    "CONCURRENT_RUNS_PER_GROUP",
    "Callable",
    "ENGINE_NOTIFY_STOP_CODES",
    "FAST_FAIL_WINDOW_SEC",
    "GitServiceError",
    "HOP_HANDOFF_FAILED_STOP_CODE",
    "HOP_HANDOFF_GRACE_SEC",
    "HOP_HANDOFF_INTERRUPTED_STOP_CODE",
    "HOP_HANDOFF_STOP_CODE",
    "HOP_TIMEOUT_SEC",
    "HTTPException",
    "INBOX_NOTIFY_STOP_CODES",
    "Iterable",
    "LAST_MESSAGE_EXCERPT_BYTES",
    "LAST_MESSAGE_MAX_BYTES",
    "LEASE_DENIAL_RECORD_LIMIT",
    "NOTIFY_STOP_CODES",
    "NO_OUTPUT_MAX_ATTEMPTS",
    "ORACLE_SETTLE_SEC",
    "OUTPUT_TAIL_BYTES",
    "Optional",
    "PARK_NOTIFY_STOP_CODES",
    "PROVIDER_UNAVAILABLE_CODE",
    "PROVIDER_UNAVAILABLE_MESSAGE",
    "Path",
    "RESTART_MAX_ATTEMPTS_DEFAULT",
    "RESUMABLE_STOP_CODES",
    "RETRY_MIN_REMAINING_SEC",
    "REVIEW_CAP_REACHED_STOP_CODE",
    "REVIEW_COUNT_DEFAULT",
    "REVIEW_EXHAUSTED_STOP_CODE",
    "REVIEW_HOP_KIND",
    "REVIEW_LOCUS_UNSPECIFIED",
    "REVIEW_NO_VERDICT_STOP_CODE",
    "REVIEW_PENDING_DOC_STATUSES",
    "REVIEW_REASON_MAX_CHARS",
    "REVIEW_REASON_MAX_FINDINGS",
    "REVIEW_REJECT_DENIED_STOP_CODE",
    "REVIEW_REJECT_FAILED_STOP_CODE",
    "REVIEW_REJECT_HEADING",
    "REVIEW_ROUNDS_NO_LIMIT",
    "REVIEW_STALLED_STOP_CODE",
    "REVIEW_STALL_ROUNDS",
    "REVIEW_STOP_CODES",
    "REVIEW_VERDICTS",
    "REVIEW_VERDICT_HOLD_STOP_CODE",
    "REWORK_HOP_KIND",
    "RUN_LIST_LIMIT_DEFAULT",
    "RUN_LIST_LIMIT_MAX",
    "RUN_TIMEOUT_BASE_SEC",
    "RUN_TIMEOUT_CAP_SEC",
    "SCRATCH_MANIFEST_NAME",
    "SCRATCH_MANIFEST_SCHEMA",
    "SCRATCH_RETENTION_DAYS",
    "SOURCE_DIRTY_FILES_LIMIT",
    "STALL_POLL_INTERVAL_SEC",
    "STALL_WATCHDOG_JOIN_SEC",
    "STEP_TIMEOUT_MAX_SEC",
    "STEP_TIMEOUT_MIN_SEC",
    "WORK_HOP_KIND",
    "_AUTH_HEADER_RE",
    "_BEARER_TOKEN_RE",
    "_CHAT_TOOL_DESC",
    "_CHAT_TOOL_NAME",
    "_CHAT_TOOL_SCHEMA",
    "_DECIDE_TOOL_DESC",
    "_DECIDE_TOOL_NAME",
    "_DECIDE_TOOL_SCHEMA",
    "_INITIAL_SOURCE_SYNC_FAILED_COPY",
    "_INITIAL_SYNC_SAFE_SKIP_REASONS",
    "_PROMPT_ECHO_MIN_LEN",
    "_REGISTER_TOOL_DESC",
    "_REGISTER_TOOL_NAME",
    "_REGISTER_TOOL_SCHEMA",
    "_RESOLVE_TOOL_DESC",
    "_RESOLVE_TOOL_NAME",
    "_RESOLVE_TOOL_SCHEMA",
    "_RUN_ID_COLLISION_COPY",
    "_RUN_ID_RE",
    "_SCOPE_PROBES",
    "_TIMEOUT_KINDS",
    "_WORKTREE_UNAVAILABLE_COPY",
    "_absolute_cap_sec",
    "_absolute_remaining_sec",
    "_active_run_for_group",
    "_adopt_continuation_token",
    "_api_bound_request",
    "_api_execute",
    "_api_help_prompt",
    "_api_read_document",
    "_append_engine_review_clause",
    "_apply_stop_row",
    "_atomic_write_manifest",
    "_auto_reject",
    "_auto_resume",
    "_auto_resume_lock",
    "_bind_register_context",
    "_broadcast",
    "_call_anthropic",
    "_call_issue_builder",
    "_call_openai",
    "_canonicalize_cli_prompt",
    "_checkpoint_document_review_loop",
    "_claim_watchdog_kill",
    "_classify_end_reason",
    "_cleanup_retained_scratches",
    "_clear_handoff_row",
    "_cli_execute",
    "_continuation_docs_target",
    "_conversation_context",
    "_conversation_turn_register",
    "_create_scratch",
    "_deadline_iso",
    "_delete_owned_scratch",
    "_ensure_initial_source_sync",
    "_execute_provider_chain",
    "_finalize_run",
    "_format_span",
    "_git_status_paths",
    "_group_resume_lock",
    "_group_resume_locks",
    "_group_resume_locks_guard",
    "_handoff_bundle",
    "_has_pending_question",
    "_hop_item_seq_or_none",
    "_hop_worker_item_seq",
    "_hop_worker_rows",
    "_http_error",
    "_http_post_json",
    "_inbox_register",
    "_inject_hop_notes",
    "_insert_document_review_loop",
    "_instruction_mode_fallback_applied",
    "_is_group_worktree",
    "_is_reparse_or_symlink",
    "_judge_hop",
    "_known_run_prompts",
    "_known_run_raw_tokens",
    "_latest_review_of",
    "_log_review_annotation_failure",
    "_manifest_for",
    "_map_lookup",
    "_mark_scratch_completed",
    "_maybe_auto_resume_hop",
    "_next_incomplete_item_seq",
    "_next_run_id",
    "_no_output_detail",
    "_normalize_ws",
    "_normalized_instruction_mode",
    "_notify_chain_failure_if_needed",
    "_note_issued_prompt",
    "_note_issued_raw_token",
    "_now_mono",
    "_open_q_doc_ids",
    "_oracle_doc_id",
    "_oracle_new_docs",
    "_paired_report_row",
    "_park_handoff",
    "_parse_rejection_history",
    "_paused_row_resume_state",
    "_pending_review_slot",
    "_persist_register_context_failures",
    "_persist_run_record",
    "_persisted_register_failures",
    "_prepare_retry_token",
    "_prioritize_chain",
    "_probe",
    "_probe_base_dirty",
    "_probe_conversation_head",
    "_probe_doc_reviews",
    "_probe_doc_revision",
    "_probe_sequence_max_item",
    "_probe_test_runs",
    "_progress_watchdog_loop",
    "_project_scratch_root",
    "_provider_brief",
    "_provider_name_of",
    "_reclaim_orphan_lease_token",
    "_record_orphaned_lease_run",
    "_recover_cli_last_message",
    "_redact_secrets",
    "_register_envelope",
    "_remaining_sec",
    "_require_group_worktree",
    "_reset_attempt_state",
    "_resolve_agent_api_base",
    "_resolve_cli_launch",
    "_resolve_conflict",
    "_resolve_continuation_hop_note",
    "_resolve_continuation_hop_override",
    "_resolve_continuation_hop_provider",
    "_resolve_restart_max_attempts",
    "_resolve_stop_code",
    "_resolve_timeout_diagnostics",
    "_resolve_timeout_sec",
    "_resolve_transport_api_base",
    "_restore_document_review_loop",
    "_resumable_reviewer_overrides",
    "_retry_eligible",
    "_retry_provider_chain",
    "_retry_remaining_sec",
    "_review_already_rejected",
    "_review_findings",
    "_review_hop_recovery_open",
    "_review_hop_recovery_run",
    "_review_key",
    "_run_counter",
    "_run_counter_floor_date",
    "_run_detail_from_row",
    "_run_list_item_live",
    "_run_list_item_stored",
    "_run_register_context",
    "_runs",
    "_runs_lock",
    "_safe_scratch_log",
    "_sanitize_diagnostic_base",
    "_sanitize_project_name",
    "_scope_oracle",
    "_scope_oracle_retry_open",
    "_scope_oracle_retry_run",
    "_sequence_completion_state",
    "_settle_and_judge",
    "_settle_gate_pass",
    "_shell_kind",
    "_spawn_auto_resume",
    "_spawn_review_hop",
    "_spawn_rework_hop",
    "_stall_remaining_sec",
    "_start_progress_watchdog",
    "_stop_progress_watchdog",
    "_stop_reason_text",
    "_tool_result_msg",
    "_uses_scope_oracle",
    "_validate_scratch_manifest",
    "_work_landed",
    "_worker",
    "_worker_source_kind",
    "_workflow_decide",
    "_write_handoff_row",
    "active_all",
    "active_review_selection",
    "ai_run_succeeded",
    "ai_execution_policy_service",
    "ai_settings_service",
    "api_server_tools",
    "build_auto_reject_reason",
    "build_document_review_loop_history",
    "cancel_run",
    "check_expected_progress",
    "clear_auto_resume",
    "compute_review_baseline",
    "datetime",
    "db_conversation_turns",
    "db_docs",
    "db_git",
    "db_group_ai_leases",
    "db_projects",
    "db_question_items",
    "db_questions",
    "db_reviews",
    "db_test_runs",
    "db_tokens",
    "db_wfseq",
    "document_review_loop_payload",
    "excerpt",
    "finished_payload",
    "force_release_group_lease",
    "get_active_status",
    "get_run_detail",
    "get_run_record",
    "get_status",
    "get_store",
    "git_service",
    "has_active_run",
    "hashlib",
    "invoke_mention_service",
    "is_resumable",
    "is_run_live",
    "json",
    "list_live_runs",
    "list_runs",
    "list_runtime_providers",
    "logger",
    "logging",
    "mark_chain_stop",
    "mark_group_lease_denied",
    "mark_user_paused",
    "now_iso",
    "os",
    "pause_run",
    "peek_auto_resume",
    "pop_auto_resume",
    "previous_timeout_handoff",
    "process_runner",
    "prompt_digest",
    "q_service",
    "re",
    "register_binding",
    "release_paused_chain",
    "request_auto_resume",
    "resolve_document_review_loop_gate",
    "resolve_loop_provider",
    "resolve_pinned_provider_name",
    "resolve_review_count",
    "resolve_review_gate",
    "resolve_reviewer",
    "resolve_round_limit",
    "resolve_step_executor",
    "resolve_stored_step_note",
    "restart_max_attempts_choices",
    "resume_chain",
    "review_finding_digest",
    "review_rounds_remain",
    "run_review_gate",
    "shutil",
    "stamp_chain_stop",
    "start_run",
    "startup_recover_handoffs",
    "startup_recover_leases",
    "stop_reason_text",
    "storage_paths",
    "stored_hop_provider",
    "template_provision",
    "threading",
    "time",
    "timedelta",
    "timezone",
    "token_service",
    "urllib",
]
