CREATE TABLE agents(agent_id TEXT PRIMARY KEY,name TEXT NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 100),enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN(0,1)),location TEXT NOT NULL CHECK(location IN('local','remote')),connection_mode TEXT,local_executable_path TEXT,configured_ai_cli INTEGER NOT NULL DEFAULT 0 CHECK(configured_ai_cli IN(0,1)),configured_ai_api INTEGER NOT NULL DEFAULT 0 CHECK(configured_ai_api IN(0,1)),configured_storage INTEGER NOT NULL DEFAULT 0 CHECK(configured_storage IN(0,1)),reported_ai_cli INTEGER CHECK(reported_ai_cli IN(0,1)),reported_ai_api INTEGER CHECK(reported_ai_api IN(0,1)),reported_storage INTEGER CHECK(reported_storage IN(0,1)),last_seen_at TEXT,agent_version TEXT,protocol_version INTEGER,os TEXT,architecture TEXT,protocol_compatibility TEXT NOT NULL DEFAULT 'unknown' CHECK(protocol_compatibility IN('unknown','compatible','incompatible')),last_rejected_protocol_version INTEGER,last_protocol_rejection_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,CHECK((reported_ai_cli IS NULL AND reported_ai_api IS NULL AND reported_storage IS NULL)OR(reported_ai_cli IS NOT NULL AND reported_ai_api IS NOT NULL AND reported_storage IS NOT NULL)),CHECK((protocol_compatibility='incompatible' AND last_rejected_protocol_version IS NOT NULL AND last_protocol_rejection_at IS NOT NULL)OR(protocol_compatibility<>'incompatible' AND last_rejected_protocol_version IS NULL AND last_protocol_rejection_at IS NULL)),CHECK((location='local' AND connection_mode IS NULL AND reported_ai_cli IS NULL AND reported_ai_api IS NULL AND reported_storage IS NULL AND last_seen_at IS NULL AND agent_version IS NULL AND protocol_version IS NULL AND os IS NULL AND architecture IS NULL AND protocol_compatibility='unknown')OR(location='remote' AND connection_mode='agent_pull' AND local_executable_path IS NULL)));
CREATE TRIGGER agents_location_immutable BEFORE UPDATE OF location ON agents WHEN NEW.location<>OLD.location BEGIN SELECT RAISE(ABORT,'agent location is immutable'); END;
CREATE TABLE agent_credentials(credential_id TEXT PRIMARY KEY,agent_id TEXT NOT NULL REFERENCES agents(agent_id) ON DELETE RESTRICT,credential_digest TEXT NOT NULL UNIQUE CHECK(length(credential_digest)=64 AND credential_digest NOT GLOB '*[^0-9a-f]*'),pepper_id TEXT NOT NULL,issued_at TEXT NOT NULL,revoked_at TEXT CHECK(revoked_at IS NULL OR revoked_at>=issued_at),last_heartbeat_at TEXT);
CREATE INDEX idx_agent_credentials_agent ON agent_credentials(agent_id);
CREATE UNIQUE INDEX uq_agent_credentials_active ON agent_credentials(agent_id) WHERE revoked_at IS NULL;
CREATE TRIGGER agent_credentials_no_delete BEFORE DELETE ON agent_credentials BEGIN SELECT RAISE(ABORT,'credential history cannot be deleted'); END;
CREATE TABLE agent_enrollments(enrollment_id TEXT PRIMARY KEY,agent_id TEXT NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,token_digest TEXT NOT NULL UNIQUE CHECK(length(token_digest)=64 AND token_digest NOT GLOB '*[^0-9a-f]*'),pepper_id TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL CHECK(expires_at>created_at),consumed_at TEXT,revoked_at TEXT,CHECK(consumed_at IS NULL OR revoked_at IS NULL));
CREATE INDEX idx_agent_enrollments_agent ON agent_enrollments(agent_id);
CREATE UNIQUE INDEX uq_agent_enrollments_pending ON agent_enrollments(agent_id) WHERE consumed_at IS NULL AND revoked_at IS NULL;
