"""Pytest configuration for FlowGate tests — shared fixtures and setup."""
import os
import shutil
import sqlite3
import subprocess
import tempfile
from pathlib import Path

import pytest

os.environ.setdefault("TESTING", "1")
os.environ.setdefault("SECRET_KEY", "test-secret-key-for-testing-only-32c")

_SERVER_DIR = Path(__file__).resolve().parents[1]
_MIGRATIONS_DIR = _SERVER_DIR / "sql" / "migrations" / "sqlite"
_REPO_ROOT = _SERVER_DIR.parent


# ── 저장소 오염 감시자 (0382 B0001 / NR0003 제안 2-b) ─────────────────────────
#
# 사고의 1단계는 "테스트가 저장소 안에 폴더를 만든다"였고, 그 폴더는 화면에 안 뜨는
# 종류라 아무도 못 봤다. 지침을 늘리는 대신 기계가 잡는다: 세션이 끝날 때 저장소에
# 새로 생긴 흔적이 있으면 **실패**시키고 무엇이 어디에 남았는지 이름을 찍는다.
# 경고로 두면 아무도 안 본다(NR §8-2 권고).

# 스크래치 디렉터리 이름 규칙. .gitignore 에 걸리면 git 은 안 보여주므로, 이름으로도
# 본다 — 저장소 안에 썼다는 사실 자체가 잡아야 할 일이다.
_SCRATCH_GLOB = ".test-tmp*"
# 전수 탐색(rglob)은 node_modules 때문에 세션마다 수 초를 먹는다. 실제로 흔적이
# 생겼던 자리만 본다: 저장소 루트, server/, server/tests/, client/.
_SCRATCH_SCAN_DIRS = (
    _REPO_ROOT, _SERVER_DIR, _SERVER_DIR / "tests", _REPO_ROOT / "client",
)
_POLLUTION_LIST_MAX = 20


def _repo_pollution_snapshot():
    """저장소에 남아 있는 흔적의 스냅샷. git 을 못 쓰면 None(감시 생략)."""
    if shutil.which("git") is None:
        return None
    proc = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard", "-z"],
        cwd=str(_REPO_ROOT), capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return None
    found = {path for path in (proc.stdout or "").split("\0") if path}
    for base in _SCRATCH_SCAN_DIRS:
        if not base.is_dir():
            continue
        for path in base.glob(_SCRATCH_GLOB):
            found.add(str(path.relative_to(_REPO_ROOT)).replace("\\", "/"))
    return found


@pytest.fixture(scope="session", autouse=True)
def repo_pollution_guard():
    """테스트가 저장소 안에 남긴 것이 있으면 세션을 실패시킨다."""
    before = _repo_pollution_snapshot()
    yield
    after = _repo_pollution_snapshot()
    if before is None or after is None:
        return
    leaked = sorted(after - before)
    if not leaked:
        return
    shown = "\n".join(f"  - {path}" for path in leaked[:_POLLUTION_LIST_MAX])
    more = "" if len(leaked) <= _POLLUTION_LIST_MAX else f"\n  ... 외 {len(leaked) - _POLLUTION_LIST_MAX}개"
    pytest.fail(
        "테스트가 저장소 안에 파일을 남겼습니다 (0382 B0001 재발 방지).\n"
        f"새로 생긴 항목 {len(leaked)}개:\n{shown}{more}\n"
        "스크래치는 저장소 밖에 만드십시오 — server/tests/scratch_support.py 의 "
        "session_scratch() 를 쓰면 됩니다.",
        pytrace=False,
    )


# ── Host capabilities and what they silently take with them ──────────────────
#
# flowgate.default.0394 T0004 (NR0003 §5.2 / §13-10).
#
# Nine places in this suite skip when the host cannot do something — no git binary, no
# symlinks, no run.bat, an unimportable module. Skipping is the right behaviour; being
# quiet about it is not. `test_git_integration_0115.py` alone is 107 cases, and on a host
# without git all 107 vanish and the run still ends "failed 0" — the same words a full
# green run prints. R0001 §8 calls for a green suite AND for intentional skips to be
# explicit, and a bare skip count cannot tell "we meant to skip this" from "this host
# could not run it".
#
# So the capabilities are named in one place and reported in two directions: the header
# says up front what this host can do, and the summary says afterwards what that cost in
# tests. And because a report nobody reads is not a gate, FLOWGATE_REQUIRE_FULL_SUITE=1
# turns any missing capability into a failure — that is what a release/Full run sets, so
# "green" there means the whole suite actually ran.

def _git_available() -> bool:
    return shutil.which("git") is not None


def _symlinks_available() -> bool:
    """Windows needs Developer Mode or admin rights, so this is a real host difference."""
    try:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / "target"
            target.mkdir()
            (Path(tmp) / "link").symlink_to(target, target_is_directory=True)
        return True
    except (OSError, NotImplementedError):
        return False


# name -> (label, probe, required_for_a_full_run)
#
# `run.bat` is reported but not required: setup.ps1 generates it and .gitignore hides it,
# so it is legitimately absent on a fresh clone and demanding it would make the strict
# mode below something everyone turns off. The other three are things a machine either
# has or should get before claiming it ran the whole suite.
CAPABILITIES: dict[str, tuple[str, callable, bool]] = {
    "git": ("git binary on PATH", _git_available, True),
    "symlinks": ("symlink creation", _symlinks_available, True),
    "api_source_tree": (
        "server/modules/flow_gate/api present",
        lambda: (_SERVER_DIR / "modules" / "flow_gate" / "api").is_dir(),
        True,
    ),
    "run_bat": (
        "run.bat (generated by setup.ps1)",
        lambda: (_SERVER_DIR.parent / "run.bat").is_file(),
        False,
    ),
}

# Skip reasons, as written at the skip site, mapped to the capability they stand for.
# A reason that matches nothing is reported under "other" rather than dropped.
_REASON_TO_CAPABILITY = (
    ("git", "git"),
    ("symlink", "symlinks"),
    ("api source tree", "api_source_tree"),
    ("run.bat", "run_bat"),
    ("flowgate_helper", "other"),
    ("sqloader", "other"),
)

_capability_state: dict[str, bool] = {}
_skips_by_capability: dict[str, int] = {}


def _classify_skip(reason: str) -> str:
    lowered = (reason or "").lower()
    # 계층 유예는 호스트 능력 부족이 아니다. 'other' 로 세면 --tier=fast 한 번에
    # 1,800 건이 그 줄로 들어가, 정작 아무도 계획하지 않은 skip 을 드러내려고 만든
    # 자리가 계층 유예에 파묻힌다 (0394 T0014).
    if _TIER_SKIP_MARK in lowered:
        return "tier"
    for needle, capability in _REASON_TO_CAPABILITY:
        if needle in lowered:
            return capability
    return "other"


# ── 실행 계층 Fast / Standard / Full ──────────────────────────────────────────
#
# flowgate.default.0394 T0004 (R0001 §6, NR0003 §10.4 / §13-12).
#
# NR0003 §10.1 measured where the 474 seconds go: the 40 slowest tests together are 15%
# of it, and the other 85% is spread thinly across 3,223 cases. Deleting slow tests
# therefore buys nothing, which is why R0001 §6 asks for tiers instead — and why this is
# a selection mechanism, not a cleanup.
#
# A test's tier is decided in two steps:
#
#   1. An explicit `@pytest.mark.fast` / `.standard` / `.full` (on the test, its class or
#      the module's `pytestmark`) always wins. That is the escape hatch for anything the
#      rule below gets wrong, and the only thing a new test has to know about.
#   2. Otherwise the tier is derived from what the module's source actually does, using
#      the classification NR0003 §10.2 measured:
#        fast      — no TestClient, no subprocess/git, no sleep
#        standard  — everything except git/subprocess work and e2e/dialect/migration files
#        full      — the rest
#
# Deriving rather than keeping a list is the point. NR0003 §10.4 warned that a list of
# files leaves new files in no tier at all; here a new file is classified the moment it
# is written, by the same rule as everything else, and a file that needs to say otherwise
# says so in one line at the top of itself.
#
# `--tier=full` (the default) selects everything, so nothing about an ordinary run changes.

_TIER_ORDER = ("fast", "standard", "full")

# Level 1 excludes anything that starts a server, shells out, or waits on the clock.
_NOT_FAST = ("TestClient", "subprocess", "sleep(", '"git"', "'git'")
# Level 2 additionally excludes the git/worktree/e2e/dialect families.
_NOT_STANDARD_TEXT = ("subprocess", '"git"', "'git'")
_NOT_STANDARD_NAME = ("_e2e", "dialect", "migration", "worktree", "git_")

_tier_cache: dict[str, str] = {}

# 유예된 테스트가 달고 가는 skip 사유의 꼬리표. 요약이 이 문자열로 유예 건수를 세므로
# 아래 marker 문구와 반드시 같이 움직여야 한다.
_TIER_SKIP_MARK = "(--tier)"

# 계층 요약은 수집 훅이 아니라 **실제로 나온 리포트**에서 센다.
# pytest-xdist 를 쓰면 수집 훅은 워커 프로세스 안에서 돌기 때문에, 거기서 모듈 전역에
# 담아 둔 값은 요약을 찍는 컨트롤러에게 보이지 않는다. 실제로 그랬다 —
# `--tier=fast -n auto` 는 117 건을 건너뛰고도 "이 실행은 전체가 아닙니다" 를 한 줄도
# 찍지 않았다. NR0003 §5.2 가 말하는 조용한 skip 이 병렬 문으로 되돌아온 것이다.
# 리포트는 워커에서 컨트롤러로 전달되므로, 여기서 세면 두 방식 모두에서 남는다.
_items_started = 0
_tier_deferred = 0


def _tier_for_module(path: Path) -> str:
    """Derived tier for a test module — see the note above for the rule."""
    key = str(path)
    cached = _tier_cache.get(key)
    if cached:
        return cached

    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        text = ""
    name = path.name

    if not any(needle in text for needle in _NOT_FAST):
        tier = "fast"
    elif (
        not any(needle in text for needle in _NOT_STANDARD_TEXT)
        and not any(needle in name for needle in _NOT_STANDARD_NAME)
    ):
        tier = "standard"
    else:
        tier = "full"

    _tier_cache[key] = tier
    return tier


def _declared_tier(item) -> "str | None":
    """An explicit marker, if the test (or its class/module) carries one."""
    for tier in _TIER_ORDER:
        if item.get_closest_marker(tier) is not None:
            return tier
    return None


# ── 병렬 실행은 파일을 쪼개지 않는 방식으로만 ────────────────────────────────
#
# flowgate.default.0394 T0014 (NR0003 §10.3 / §13-13).
#
# pytest-xdist 의 기본 분배(`--dist load`)는 **테스트 한 건씩** 워커에 흩뿌린다.
# 이 저장소는 그렇게 나눌 수 없다. 모듈 스코프 픽스처(임시 DB, FLOWGATE_* 환경변수
# 되돌리기)와 import 시점에 저장소 루트를 심는 스위트가 있어서, 한 파일이 두 프로세스로
# 찢어지면 절반은 픽스처가 세워지지 않은 자리에서 돈다. 그 실패는 워커 배분에 따라
# 모습이 바뀌므로 "가끔 빨간불" 로 보이고, 결국 병렬 실행 자체가 못 믿을 것으로
# 취급된다 — 도입을 검증하러 온 자리에서 가장 피해야 할 결말이다.
#
# 그래서 안전하지 않은 분배로 들어온 병렬 실행은 시작 자체를 거절한다. 문서에 적어 두는
# 것만으로는 부족하다. 옵션 하나를 빠뜨린 사람은 문서를 다시 읽지 않고, 대신 이상한
# 실패를 보게 된다.
#
# 안전: loadfile(파일 단위) · loadscope(모듈/클래스 단위) — 둘 다 한 파일을 한 워커에 둔다.
# 거절: load(기본) · worksteal · loadgroup · each.
_SAFE_DIST_MODES = ("no", "loadfile", "loadscope")


def _dist_mode_problem(numprocesses, dist) -> "str | None":
    """병렬 설정이 이 저장소에서 안전하면 None, 아니면 거절 사유."""
    if not numprocesses:
        return None
    if dist in _SAFE_DIST_MODES:
        return None
    return (
        f"병렬 실행에 --dist {dist} 는 쓸 수 없습니다. 이 저장소의 테스트는 모듈 스코프 "
        "임시 DB 와 import 시점 환경변수를 파일 단위로 공유하므로, 한 파일이 여러 워커로 "
        "찢어지면 픽스처가 세워지지 않은 채 실행됩니다 (NR0003 §10.3). "
        "`-n auto --dist loadfile` 로 실행하십시오."
    )


def pytest_addoption(parser):
    parser.addoption(
        "--tier",
        action="store",
        default="full",
        choices=list(_TIER_ORDER),
        help="Execution tier: fast (development) / standard (task completion) / full (release).",
    )


def pytest_collection_modifyitems(config, items):
    requested = config.getoption("--tier")
    if requested == "full":
        return   # the default: run everything, exactly as before this option existed

    ceiling = _TIER_ORDER.index(requested)
    for item in items:
        tier = _declared_tier(item) or _tier_for_module(Path(str(item.fspath)))
        if _TIER_ORDER.index(tier) > ceiling:
            item.add_marker(
                pytest.mark.skip(
                    reason=f"tier {tier} > requested {requested} {_TIER_SKIP_MARK}"
                )
            )


def pytest_configure(config):
    # Probe here, not in pytest_report_header: `-q` suppresses the header entirely, and
    # the summary would then have nothing to report — which is the exact silence this
    # whole block exists to remove, and every CI invocation uses -q.
    for name, (_label, probe, _required) in CAPABILITIES.items():
        _capability_state[name] = _safe_probe(probe)

    # 컨트롤러에서만 본다. 워커는 자기 몫을 순차 실행하므로 dist 설정이 없다.
    if getattr(config, "workerinput", None) is None:
        problem = _dist_mode_problem(
            getattr(config.option, "numprocesses", None),
            getattr(config.option, "dist", "no"),
        )
        if problem:
            raise pytest.UsageError(problem)


def pytest_report_header(config):
    missing = [name for name, ok in _capability_state.items() if not ok]
    line = "host capabilities: " + ", ".join(
        f"{name}={'yes' if ok else 'NO'}" for name, ok in _capability_state.items()
    )
    if missing:
        line += (
            f"\n  ⚠ missing: {', '.join(missing)} — the tests that need them will be skipped,"
            " NOT run. Set FLOWGATE_REQUIRE_FULL_SUITE=1 to make that a failure."
        )
    requested = config.getoption("--tier", default="full")
    if requested != "full":
        line += (
            f"\nexecution tier: {requested} — 이 실행은 전체가 아닙니다. release 전에는 "
            f"--tier 없이(=full) 한 번 돌리십시오."
        )
    return line


def pytest_runtest_logreport(report):
    global _items_started, _tier_deferred

    # setup 리포트는 테스트 한 건에 정확히 하나씩 나온다 — 건너뛴 것까지 포함해서.
    # 그래서 이것이 "이 실행이 손에 쥔 전체 건수" 다.
    if report.when == "setup":
        _items_started += 1

    if report.skipped:
        reason = report.longrepr[2] if isinstance(report.longrepr, tuple) else str(report.longrepr)
        key = _classify_skip(reason)
        if key == "tier":
            _tier_deferred += 1
        _skips_by_capability[key] = _skips_by_capability.get(key, 0) + 1


def pytest_sessionfinish(session, exitstatus):
    """워커라면 자기가 모은 환경변수 누출을 컨트롤러 몫으로 실어 보낸다."""
    workeroutput = getattr(session.config, "workeroutput", None)
    if workeroutput is not None:
        workeroutput["flowgate_env_leaks"] = list(_env_leaks)


@pytest.hookimpl(optionalhook=True)
def pytest_testnodedown(node, error):
    """워커가 내려갈 때 그 워커의 누출 보고를 컨트롤러 목록에 합친다.

    optionalhook 이라 pytest-xdist 가 없는 환경에서도 conftest 는 그대로 읽힌다.
    """
    for line in (getattr(node, "workeroutput", None) or {}).get("flowgate_env_leaks", []):
        if line not in _env_leaks:
            _env_leaks.append(line)


def pytest_terminal_summary(terminalreporter, exitstatus, config):
    if _env_leaks:
        terminalreporter.write_sep("=", "환경변수 누출 (0394 T0004)")
        for line in _env_leaks:
            terminalreporter.write_line(f"  · {line}")
        terminalreporter.write_line(
            "  이 실행에서는 되돌려 놓았지만, 근원은 해당 모듈입니다 — 환경변수를 지우지 "
            "말고 원래 값으로 복원하십시오. 지우면 import 시점에 값을 발행한 다른 스위트의 "
            "것까지 함께 사라집니다."
        )

    requested = config.getoption("--tier", default="full")
    workers = getattr(config.option, "numprocesses", None)
    if _tier_deferred:
        # 소리 내어 말한다. 계층 실행의 "실패 0" 은 전부 통과가 아니고,
        # NR0003 §5.2 는 통째로 그 차이에 관한 이야기다.
        #
        # 실행 건수에서는 **건너뛴 것을 전부** 뺀다. 계층 유예만 빼면 호스트 능력 때문에
        # 빠진 건이 실행 건수에 섞인다 — `--tier=fast` 가 "1614건 실행" 이라고 찍는데
        # pytest 는 1613 passed / 1654 skipped 를 찍고, 그 한 건이 바로 run.bat 이 없어
        # 빠진 건이었다. 조용한 skip 을 드러내려고 만든 줄이 스스로 조용한 skip 을
        # 하나 감추고 있었던 셈이라, 여기서는 그 한 건이 가장 틀린 한 건이다 (0394 T0014).
        other_skipped = sum(_skips_by_capability.values()) - _tier_deferred
        ran = _items_started - _tier_deferred - other_skipped
        extra = f" 그 밖의 사유로 {other_skipped}건 더 건너뜀." if other_skipped else ""
        terminalreporter.write_sep("=", "실행 계층 (0394 T0004)")
        terminalreporter.write_line(
            f"  --tier={requested}: {ran}건 실행, "
            f"{_tier_deferred}건은 상위 계층 몫으로 건너뜀.{extra} "
            f"이 실행의 '실패 0' 은 전체 통과가 아닙니다."
        )
    if workers:
        terminalreporter.write_sep("=", "병렬 실행 (0394 T0014)")
        terminalreporter.write_line(
            f"  워커 {workers}개 / --dist {getattr(config.option, 'dist', 'no')} — "
            f"파일 단위로만 나눕니다. 결과 판정은 순차 실행과 같아야 합니다."
        )

    if not _skips_by_capability and all(_capability_state.values()):
        return

    terminalreporter.write_sep("=", "환경 능력 / skip 보고 (0394 T0004)")
    for name, (label, _probe, required) in CAPABILITIES.items():
        ok = _capability_state.get(name, True)
        skipped = _skips_by_capability.get(name, 0)
        mark = "✓" if ok else "✗"
        note = "" if required else "  (full 실행 요건 아님)"
        terminalreporter.write_line(
            f"  {mark} {name:<16} {label:<45} skipped={skipped}{note}"
        )
    other = _skips_by_capability.get("other", 0)
    if other:
        terminalreporter.write_line(f"    (그 밖의 사유로 건너뛴 테스트: {other})")

    missing = [name for name, ok in _capability_state.items() if not ok]
    if missing:
        terminalreporter.write_line(
            "  ⚠ 위 ✗ 항목 때문에 빠진 테스트는 실행되지 않았습니다 — 실패 0 이 곧 "
            "전부 통과는 아닙니다."
        )


@pytest.fixture(scope="session", autouse=True)
def require_full_suite_when_asked():
    """Fail the run when a Full-level run lands on a host that cannot do everything.

    Off by default so a developer laptop keeps skipping quietly-but-visibly; on for the
    Full tier, where the whole point is that nothing was left out.
    """
    if os.environ.get("FLOWGATE_REQUIRE_FULL_SUITE", "").strip() not in ("1", "true", "TRUE"):
        yield
        return

    missing = [
        name for name, (_label, _probe, required) in CAPABILITIES.items()
        if required and not _capability_state.get(name, False)
    ]
    if missing:
        pytest.fail(
            "FLOWGATE_REQUIRE_FULL_SUITE=1 인데 이 호스트가 갖추지 못한 능력이 있습니다: "
            f"{', '.join(missing)}. 이대로 돌리면 해당 테스트가 조용히 빠진 채 '실패 0' 이 "
            "나옵니다 (NR0003 §5.2). 능력을 갖춘 호스트에서 돌리거나, 이 실행이 전체 "
            "검증이 아님을 인정하고 변수를 끄십시오.",
            pytrace=False,
        )
    yield


def _safe_probe(probe) -> bool:
    try:
        return bool(probe())
    except Exception:
        return False


# ── FLOWGATE_* 환경변수는 빌린 것이다 — 모듈 경계에서 되돌린다 ────────────────
#
# flowgate.default.0394 T0004 (R0001 §5.1 — 순서·환경에 따라 결과가 달라지는 테스트).
#
# 많은 스위트가 **import 시점에** 자기 저장소 루트를 발행한다
# (`os.environ["FLOWGATE_STORAGE_DIR"] = tempfile.mkdtemp(...)`). pytest 는 아무것도
# 실행하기 전에 모든 모듈을 import 하므로, 그 값들은 실행이 시작될 때 이미 다 올라와
# 있다. 그래서 어떤 테스트가 자기 값을 심었다가 끝나면서 `del` 이나 `pop` 으로 **지우면**
# 자기 것만 지우는 게 아니라 남의 것까지 지우고, 프로세스에는 저장소 루트가 아예 없는
# 상태가 남는다.
#
# 실제로 그 일이 일어나고 있었다. `test_numbering.py` 와 `test_outbound_single.py` 가
# 각각 정리 단계에서 FLOWGATE_STORAGE_DIR 을 지웠고, 그 뒤에 오는
# `test_worktree_resolution_e2e_0280.py` 는 자기 임시 루트를 잃은 채
# `ensure_worktree` 가 엉뚱한 자리에 만들어 "failed" 를 돌려주면서 **7 건이 setup 에서
# error** 로 죽었다. 그 파일만 따로 돌리면 8 건 전부 통과한다 — NR0003 §4.1 이
# "순서 의존은 없다" 고 결론 낸 자리에서, 실패가 아니라 error 로 잡히는 바람에
# `-rf` 요약에 이름이 안 찍혀 눈에 띄지 않았던 종류다.
#
# 두 파일은 각자 고쳤다. 이건 그 다음을 위한 것이다 — NR0003 §5.3 의 요지 그대로,
# 규칙이 전역이면(모듈은 환경을 빌려 쓰고 그대로 돌려준다) 검사도 전역이어야 한다.
#
# 실패시키지 않고 **되돌린 뒤 보고**한다. 되돌리는 쪽이 그 자체로 사고를 막고, 이미
# 있는 다른 누출을 새 빨간불로 바꾸지 않는다. 대신 어느 모듈이 무엇을 흘렸는지 실행
# 끝에 이름이 찍히므로, 근원에서 고칠 수 있다.

_env_leaks: list[str] = []


def _flowgate_env() -> dict:
    return {k: v for k, v in os.environ.items() if k.startswith("FLOWGATE_")}


@pytest.fixture(scope="module", autouse=True)
def flowgate_env_returned_as_found(request):
    """모듈이 바꾼 FLOWGATE_* 환경변수를 모듈이 끝날 때 원래대로 돌려놓는다."""
    before = _flowgate_env()
    yield
    after = _flowgate_env()
    if after == before:
        return

    module = getattr(request.node, "name", "?")
    for key in sorted(set(before) | set(after)):
        old_value, new_value = before.get(key), after.get(key)
        if old_value == new_value:
            continue
        if old_value is None:
            what = f"{key} 를 새로 남겼다"
            os.environ.pop(key, None)
        elif new_value is None:
            what = f"{key} 를 지웠다"
            os.environ[key] = old_value
        else:
            what = f"{key} 를 바꿔 놓았다"
            os.environ[key] = old_value
        _env_leaks.append(f"{module}: {what}")


def get_migration_files() -> list[Path]:
    """Get all migration files sorted in order."""
    files = sorted(_MIGRATIONS_DIR.glob("*.sql"))
    return files


@pytest.fixture(scope="session")
def migrated_sqlite_db(tmp_path_factory):
    """Factory -> path to a fresh sqlite file with EVERY migration applied.

    flowgate.default.0394 T0004 (NR0003 §13-6 / §7.2).

    Five suites were each carrying their own `test_db_path` fixture that built a schema
    by hand. Four of them looped over the whole migration directory; `test_auth.py` had
    frozen a subset — 001, 002 and 005 out of 87 — so the day `067a_auth_sessions.sql`
    arrived, seven auth tests died on `no such table: auth_sessions`. The schema was
    fine; the copy of it in that one file was not, and nothing tied the copies together.

    So there is one builder now, and it always applies everything. A suite that needs
    rows of its own passes them as `seed_sql`; a suite that needs a different starting
    schema does not exist.

    Unlike the per-file copies, a failing migration is NOT swallowed here. Those
    `except sqlite3.OperationalError: pass` clauses were written for the era when the
    directory could not be replayed cleanly, and they would hide exactly the breakage
    this fixture exists to catch — the whole set applying in name order is itself
    asserted by tests/test_migration_numbering.py.

    Session-scoped factory, function-scoped output: each call gets its own file, so two
    suites never share mutable state.
    """
    def _build(name: str, seed_sql: str = "") -> str:
        db_path = str(tmp_path_factory.mktemp("db") / name)
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        try:
            for migration_file in get_migration_files():
                conn.executescript(migration_file.read_text(encoding="utf-8"))
            if seed_sql:
                conn.executescript(seed_sql)
            conn.commit()
        finally:
            conn.close()
        return db_path

    return _build


@pytest.fixture(scope="session")
def all_migrations_db():
    """Create a test database with all migrations applied."""
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as f:
        db_path = f.name

    conn = sqlite3.connect(db_path, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")

    # Apply all migrations in order
    for migration_file in get_migration_files():
        try:
            sql = migration_file.read_text(encoding="utf-8")
            conn.executescript(sql)
            print(f"✓ Applied: {migration_file.name}")
        except Exception as e:
            print(f"⚠ Error in {migration_file.name}: {e}")

    # Seed required data
    conn.executescript(
        """
        INSERT OR IGNORE INTO roles(role_id,role_name,is_system,created_at,updated_at)
            VALUES
                ('role_admin','Administrator',1,datetime('now'),datetime('now')),
                ('role_manager','Manager',1,datetime('now'),datetime('now')),
                ('role_worker','Worker',1,datetime('now'),datetime('now')),
                ('role_viewer','Viewer',1,datetime('now'),datetime('now'));

        INSERT OR IGNORE INTO permissions(permission_id,permission_name,created_at)
            VALUES
                ('system.settings.manage','Manage system settings',datetime('now')),
                ('system.user.read','View users',datetime('now')),
                ('system.user.create','Create user',datetime('now')),
                ('system.user.update','Update user',datetime('now')),
                ('system.user.delete','Delete user',datetime('now')),
                ('system.user.assign_role','Assign role',datetime('now')),
                ('project.settings.read','View project settings',datetime('now')),
                ('project.settings.edit','Edit project settings',datetime('now')),
                ('project.document_type.create','Create document type',datetime('now')),
                ('project.document_type.update','Update document type',datetime('now')),
                ('project.document_type.delete','Delete document type',datetime('now'));

        INSERT OR IGNORE INTO role_permissions(role_id,permission_id)
            VALUES
                ('role_admin','system.settings.manage'),
                ('role_admin','system.user.read'),
                ('role_admin','system.user.create'),
                ('role_admin','system.user.update'),
                ('role_admin','system.user.delete'),
                ('role_admin','system.user.assign_role'),
                ('role_admin','project.settings.read'),
                ('role_admin','project.settings.edit'),
                ('role_admin','project.document_type.create'),
                ('role_admin','project.document_type.update'),
                ('role_admin','project.document_type.delete'),
                ('role_manager','project.settings.read'),
                ('role_manager','project.settings.edit'),
                ('role_manager','project.document_type.create'),
                ('role_manager','project.document_type.update'),
                ('role_manager','project.document_type.delete');

        INSERT OR IGNORE INTO projects(project_id,project_name,is_active,created_at,updated_at)
            VALUES
                ('__SYSTEM__','[System]',1,datetime('now'),datetime('now'));

        INSERT OR IGNORE INTO users(user_id,username,email,password,is_active,is_admin,first_login_required,created_at,updated_at)
            VALUES
                ('usr_admin','admin','admin@test.com','hashed_pw',1,1,0,datetime('now'),datetime('now'));

        INSERT OR IGNORE INTO user_project_roles(user_id,project_id,role_id,granted_at)
            VALUES('usr_admin','__SYSTEM__','role_admin',datetime('now'));

        INSERT OR IGNORE INTO system_settings(setting_key,setting_value,value_type,updated_at)
            VALUES('storage_root','/data/flowgate','string',datetime('now'));
    """
    )

    conn.commit()
    yield conn
    conn.close()
    os.unlink(db_path)


@pytest.fixture
def test_db(all_migrations_db):
    """공용 연결을 한 테스트에 빌려준다 — 열린 트랜잭션 없이 주고, 쓴 것은 되돌려 받는다.

    flowgate.default.0394 T0014 (NR0003 §13-13 — 병렬 안전성 검증).

    `all_migrations_db` 는 세션 스코프 연결 하나다. 네 개 파일이 그것을 공유하는데,
    그 중 `test_tokens_resolve_conflict_scope_0233.py` 는 tokens 에 INSERT 만 하고
    commit 도 정리도 하지 않는다. python 의 sqlite3 는 그 시점에 쓰기 트랜잭션을 열고
    닫지 않으므로, **다음 파일은 트랜잭션이 열린 연결을 물려받는다.**

    sqlite 의 `PRAGMA foreign_keys` 는 트랜잭션 안에서는 조용히 무시된다. 그래서
    `test_auto_approved_locale_0099.py` 가 FK 를 끄고 하는 round-trip INSERT 는 FK 가
    켜진 채로 실행돼 IntegrityError 로 죽는다 — 자기 잘못이 아니라 앞 파일 때문에.

    순차 실행에서는 이 조합이 알파벳 순서 덕분에 반대로 놓여 한 번도 드러나지 않았다
    (NR0003 §4.1 이 "순서 의존은 없다" 고 결론 낸 근거가 그 순서였다). 파일을 워커에
    나눠 주는 순간 순서가 바뀌고, 실제로 `--tier=standard -n auto --dist loadfile` 에서
    이 한 건이 빨간불이 됐다. 병렬 자체의 결함이 아니라, **병렬이 드러낸 원래 있던
    파일 간 상태 공유**다.

    그래서 연결을 넘겨줄 때와 돌려받을 때 양쪽에서 트랜잭션을 닫는다. 되돌리는 쪽이라
    세션 시작 때 commit 된 시드 데이터는 그대로 남고, 테스트가 쓴 행만 사라진다 —
    남의 테이블에 행을 남기는 것 또한 같은 뿌리의 사고다.
    """
    all_migrations_db.rollback()
    try:
        yield all_migrations_db
    finally:
        all_migrations_db.rollback()

