"""Regression guard for group 0102 R0001 (candidate B — backstop).

Every uvicorn startup path must set a finite `timeout_graceful_shutdown`, so any
stuck in-flight request (not just SSE) cannot block shutdown indefinitely if the
cooperative app-level signal is ever bypassed. Also asserts the lifespan handler
wires the cooperative `shutdown_event` (candidate A — primary mechanism).

These are static source assertions: the entry points are launch scripts / CLI
invocations that are awkward to exercise live, but trivial to drift. Pinning the
flag here keeps all paths consistent (NR0003 §4 candidate C).

`run.bat` is the Windows launcher, and it is gitignored and REGENERATED by
`setup.ps1` on every run - so the durable assertion is on the GENERATOR (group
0298 R0001). Patching only the emitted file is undone by the next setup run, and
the file is simply absent on a host that has not run setup yet, which is why the
run.bat check below skips instead of failing there.

Not covered here: the Windows deploy wrapper `flowgate.ps1`, which starts uvicorn
itself but lives OUTSIDE this repo (next to it, not in it), so no repo-relative
path can reach it. It carries the flag as of 2026-07-22.
"""
from __future__ import annotations

from pathlib import Path

import pytest

_SERVER_DIR = Path(__file__).resolve().parents[1]
_REPO_DIR = _SERVER_DIR.parent


def _read(rel_path: str) -> str:
    return (_REPO_DIR / rel_path).read_text(encoding="utf-8")


@pytest.mark.parametrize("rel_path", ["server/dev.py", "server/stg.py"])
def test_python_entrypoints_set_graceful_timeout(rel_path):
    src = _read(rel_path)
    assert "timeout_graceful_shutdown=3" in src, (
        f"{rel_path} must pass timeout_graceful_shutdown=3 to uvicorn.run "
        "(group 0102 R0001 backstop)"
    )


def test_setup_ps1_emits_run_bat_with_graceful_timeout():
    """The generator, not its output - see the module docstring."""
    src = _read("setup.ps1")
    # Command-line form: the run.bat template, the -Start path, and the closing
    # "Done." help text that tells the operator how to start the server by hand.
    shell_launches = [
        line for line in src.splitlines()
        if "-m uvicorn routers.main:app" in line
    ]
    assert len(shell_launches) >= 2, (
        "setup.ps1 no longer emits a uvicorn launch line - the run.bat template "
        "and the -Start path are both expected here"
    )
    for line in shell_launches:
        assert "--timeout-graceful-shutdown 3" in line, (
            "every uvicorn launch line in setup.ps1 must carry "
            "--timeout-graceful-shutdown 3 - run.bat is regenerated from here, "
            f"so this is where the flag has to live (group 0298 R0001): {line.strip()}"
        )
    # Array form: the hidden server setup.ps1 boots once to apply migrations.
    assert "'--timeout-graceful-shutdown', '3'" in src, (
        "the migration-boot Start-Process must pass the flag as PowerShell "
        "array tokens (group 0298 R0001)"
    )


def test_run_bat_sets_graceful_timeout():
    # Generated by setup.ps1 and gitignored: absent on a fresh clone, and on a
    # host that HAS run setup it must agree with the generator above.
    run_bat = _REPO_DIR / "run.bat"
    if not run_bat.exists():
        pytest.skip("run.bat is generated by setup.ps1; not present on this host")
    src = run_bat.read_text(encoding="utf-8")
    assert "--timeout-graceful-shutdown 3" in src, (
        "run.bat must pass --timeout-graceful-shutdown 3 to uvicorn "
        "(group 0102 R0001 backstop) - re-run setup.ps1 to regenerate it"
    )


def test_dockerfile_cmd_sets_graceful_timeout():
    src = _read("Dockerfile")
    # The flag and its value are separate CMD array tokens.
    assert '"--timeout-graceful-shutdown"' in src and '"3"' in src, (
        "Dockerfile CMD must pass --timeout-graceful-shutdown 3 to uvicorn "
        "(group 0102 R0001 backstop)"
    )


def test_lifespan_wires_cooperative_shutdown_event():
    src = _read("server/routers/main.py")
    assert "app.state.shutdown_event = asyncio.Event()" in src, (
        "lifespan must create the cooperative shutdown_event (candidate A)"
    )
    assert "app.state.shutdown_event.set()" in src, (
        "lifespan must set shutdown_event on shutdown so SSE streams stop"
    )
